### ISSUE TITLE
Switching between a city in a corp with higher employee to lower employee fucks up the employee count

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1170]

**Comment by vmesecher** [comment]
(I apologize if you already knew most of all of this - just trying to be thorough since I don't submit issues often).

The bug seems to manifest when switching to cities with higher employee counts as well (not sure if unique to my save or not - attaching, [1170Bug.txt](https://github.com/danielyxie/bitburner/files/7118812/1170Bug.txt)).

Once employee counts look fucked up, at any point, switching between two cities with the same employee count fixes them. The change appears purely cosmetic.

The employee counts and task assignments are consistent (but wrong) when switching back and forth between different cities. (For this next section, for brevity, I'll use X-X-X-X-X-X to denote employees assigned to each task, starting from the leftmost X as operations and the rightmost X as Training).

**Starting Assigments in my save**

City | Assignments | Total Employees
---- | -------------- | ------------------
Aevum | 3-3-2-2-2-0 | 12 total
Chongqing | 3-3-2-2-2-0 | 12 total
Sector-12 | 3-3-3-3-3-0 | 15 total
New Tokyo | 3-3-3-3-3-0 | 15 total
Ishima |  3-2-1-1-2-0 | 9 total
Volhaven |  3-2-1-1-2-0 | 9 total

Starting from Sector-12 or New Tokyo with correct assignments and swapping to Aevum or Chongqing gets `0-0-0-0-0-0`. Swapping from either Aevum or Chongqing to the other pair sets them them back to the correct assignments and counts.

Restarting from Aevum or Chongqing with correct assignments and swapping to Sector-12 or New Tokyo yields `0-0-3-3-3-0`, then back to either Aevum or Chongqing gets `0-0-0-0-0-0`, then back again to Sector-12 or New Tokyo gives `0-0-1-1-1-0`. Back and forth after this has no change

The above are all the same no matter which of the two paired cities you start or end in.

Starting from Sector-12 or New Tokyo with correct assignments and swapping to Ishima or Volhaven gives `0-0-0-0-0-0`. However, swapping back to Sector-12 gives `1-0-2-2-1-0`, while New Tokyo gives `0-1-2-2-1-0`.

Starting from Ishima or Volhaven then swapping to Aevum gives `0-3-2-0-3-0`, back and forth and back to Aevum gives `0-1-1-0-1-0`. With Chongqing, it's `0-3-2-2-0-0` then `0-1-1-1-0-0`.

The switches between two pairs seem to stabilize after two back and forths and then always give the same numbers. 

There's too many permutations swapping between 3 all pairs, but it doesn't seem to follow the pattern of pairs that I can; starting from different cities gives different results.

However, I will call out one really weird swap I saw. Starting from Ishima or Volhaven with correct assigments, swapping to Sector-12 gives `4-0-3-3-2-0` then back and forth again gives Sector-12 `1-0-2-2-1-0`.  Conversely, New Tokyo gives `0-3-3-3-3-0` and then `0-1-2-2-1-0`.

The 4 for Sector-12 stuck out at me because none of the cities have 4 workers assigned to a task.

Anyway, I don't have much in the way of theories, and you have probably have a better idea than I do, but I'll look through the code a bit.

**Comment by hydroflame** [comment]
I fixed this locally, I'm deploying the fix tonight.

**Comment by vmesecher** [comment]
Awesome, thanks! That was a fast fix.
