### ISSUE TITLE
Gang territory can be stuck at 0.9999999

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1914]

**Comment by kamukrass** [comment]
I can offer root cause analysis, test script and pseudocode solution proposal. Since I do not have a test setup available for bitburner source code, I invite anyone else to implement and test the solution.

#### Root Cause 
The sum of all gang territories often differs to 1 due to rounding. Sometimes more than 1, sometimes less.
0.1 + 0.2 != 0.3 -> see for example: https://floating-point-gui.de/basic/ 
So you subtract a number from one gangs territory and add the same number to another gangs territory. However, those numbers added to the gang territory values might be computed differently for the two gangs. This can result in a changed total amount of territory. Thus in some situations, players are stuck at < 100% territory because there is just no territory left. 
Game Impact: Some player gang management scripts can become buggy when this happens (like mine did).
#### Solution proposal
Currently, territory is rounded to 16 digits by default with maximum precision but rounding issues. Instead, round gang territory related computations to 1 or 2 digits less (not sure if 1 is sufficient). 

https://github.com/danielyxie/bitburner/blob/ee887de151f00c508e4f37ba94885ceeaffa36fd/src/Gang/AllGangs.ts 
For all gangs but the last one, add .toFixed(15) to the calculation (1/7). For the last gang, calculate (1 - (6 * (1/7)).toFixed(15). This way the territory is divided properly with less precision. Note: There is a difference between 6*(1/7) and 6/7. 

https://github.com/danielyxie/bitburner/blob/ee887de151f00c508e4f37ba94885ceeaffa36fd/src/Gang/Gang.ts#L224:L254
Add .toFixed(15) to the territory gain/loss calculations.

Warning! Very small territory shifts could then be rounded to zero: It could have an impact on balance. It could slow down territory wars a bit especialy with low gang power differences. This might be a "good" side-effect acutally. Else, consider updating calculateTerritoryGain().

 #### Test script
```
/** @param {NS} ns **/
export async function main(ns) {
	ns.disableLog("ALL");
	ns.print("Root cause: 0.1 + 0.2 = " + (0.1 + 0.2));
	ns.print("Rounding is a solution if precision of 1 or 2 digits less is acceptable")
	ns.print("Rounded to 14 digits: 0.1 + 0.2 = " + (0.1 + 0.2).toFixed(15));
	ns.print("Remaining problem: Territory Initialization: 7 * 1/7 rounded = " + (7 * (1/7).toFixed(15)));
	ns.print("Solution: (6 * 1/7.toFixed(15)) + 1 * (1 - 6 * 1/7.toFixed(15)) = " + ((6 * (1/7).toFixed(15)) + (1 * (1 - 6 * (1 / 7).toFixed(15)))));
	while (true) {
		// continuously monitor total territory
		// How to test: Start a new gang. Save game to a file. Load it a few hours later so progress is faster. Watch log.
		let otherGangInfos = ns.gang.getOtherGangInformation();
		let territorySum = 0;
		for (const otherGang of allGangs) {
			territorySum += otherGangInfos[otherGang].territory
		}
		ns.print("Territory sum: " + territorySum);
		await ns.sleep(2000);
	}
}
const allGangs = ["Speakers for the Dead", "The Dark Army", "The Syndicate", "Tetrads", "Slum Snakes", "NiteSec", "The Black Hand"]
```
Note that the territorySum in this test script might also be flawed due to computation inaccuracy.

**Comment by phyzical** [comment]
@kamukrass its really easy to get going, just check it out, `npm install` then `npm run build:dev` then just run the root index.html in your browser

**Comment by TheRealMaxion** [comment]
Here is an example of how far from 1 the territory can get stuck:
![image](https://user-images.githubusercontent.com/13872642/159794168-67d9cfec-3501-4924-8680-defbf678a79d.png)
