### ISSUE TITLE
Leading slash in file path causes oddness with wget and/or scp.

### ISSUE THREAD

**Issue by Xynrati** [danielyxie/bitburner#1935]
Should be standard support and handled the same everywhere

**Comment by rabirabirara** [comment]
To be specific, in the documentation (https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html?highlight=backdoor#netscript), it is noted that files not in the root directory _need_ to be referred to by absolute path.  This is a limitation that is documented as part of the game; it is not a bug per se.

However, the documentation does not mention that you *cannot* refer to files in the root directory by absolute path in arguments passed to functions like `fileExists()` or `exec()`.  This is probably the main problem (besides the inherent inconsistency of NetScript's filepath behavior) and why a few people comment on the forward-slash in file paths.

So for future users with this problem, you can do the following to standardize file paths so that they are correctly treated.  This is a NetScript 2 function.

```js
function standardize(path) {
    // remove all slashes at the start of the string
    let s = path.replace(/^\/*/g, "");
    if (s.includes("/")) {
        // the file is not in the root directory; prepend a single slash
        return "/" + s;
    } else {
        // the file is in the root directory (no slashes in the filename that aren't in front); prepend no slashes
        return s;
    }
}

**Comment by Xynrati** [comment]
Not exactly. If you do this using wget for files in the root folder, you'll cause problems.

**Comment by rabirabirara** [comment]
I see. Since your original post is quite bare, I had thought you were referring to a different problem.  Could you elaborate what your issue actually is?

**Comment by phyzical** [comment]
this issues plagued me when i first started playingill take a crack at it. ill just assume we just want it to work the same everywhere
