### ISSUE TITLE
concurrent stanek.charge says "stanek.prop"

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1951]

**Comment by lukebarone** [comment]
The code I was using causing this issue:

```js
export async function main(ns) {
    ns.print("Starting script here");
    var current = [];
    var x, y;
    for (x = 0; x < ns.stanek.width(); x++) {
        for (y = 0; y < ns.stanek.height(); y++) {
            current = ns.stanek.get(x, y)
            if (current !== undefined) {
                ns.stanek.charge(x, y);
            }
        }
    }
}
```

Error message appearing:

```nolang
Cannot read properties of undefined (reading 'width')
stack:
TypeError: Cannot read properties of undefined (reading 'width')
at Module.main (stanek.ns:7:31)
at executeJSScript (https://danielyxie.github.io/bitburner/main.bundle.js:1:491223)
```

Discord dicussion: https://discord.com/channels/415207508303544321/921120953273036882/921121226913628221

**Comment by Master-Guy** [comment]
Error related to the bug:
`Concurrent calls to Netscript functions not allowed! Did you forget to await hack(), grow(), or some other promise-returning function? (Currently running: stanek.prop tried to run: stanek.prop)`
https://discord.com/channels/415207508303544321/921120953273036882/921121838069854290

Message posted by @lukebarone is a non-issue:
In Discord, the code posted was with capital `Stanek` instead of `stanek`.
User confirmed it working afterwards: https://discord.com/channels/415207508303544321/921120953273036882/921122883303002112
