### ISSUE TITLE
Hacking from home bypasses hacking level requirement

### ISSUE THREAD

**Issue by paullallier** [danielyxie/bitburner#2090]
Version: MacOS/Steam
Immediately after installing an augmentation, using this script:

---only_hack.ns---
```/** @param {NS} ns **/
export async function main(ns) {
    var target = ns.args[0];
    ns.nuke(target);
}
```

If I run this command from home, I can hack harakiri-sushi immediately, even if my hacking level is still 1.

`run only-hack.ns harakiri-sushi`

If I buy all the hacking program from the dark web and add them to the script, I can hack all the servers in the game, irrespective of hacking level.

I assume this is a bug rather than intended behaviour?  I couldn't see anyone else raising it.

(Nice game, BTW!)

**Comment by AlphaOneProject** [comment]
After bypassing the check for hacking level I did before hacking I can confirm it does indeed obtain root permissions regardeless of the hacking level.

**Comment by theit8514** [comment]
You are confusing required hacking level for *hack* vs the required ports to *nuke*. To root the server you just need the required number of ports opened on it and then nuke it. To hack a server for money, you need the server to be rooted and the amount of hacking skill level indicated.

Could be that some wording/ordering needs to be changed here, since root and required hacking skill are on the same line.
```
[2021-12-22 12:48:38 PM] --------omega-net
[2021-12-22 12:48:38 PM] ----------Root Access: YES, Required hacking skill: 217
[2021-12-22 12:48:38 PM] ----------Number of open ports required to NUKE: 2
[2021-12-22 12:48:38 PM] ----------RAM: 32.00GB
```
With hacking 177:
![image](https://user-images.githubusercontent.com/1175401/147135495-865b2819-6f14-4fc9-8697-feca4f6e7c3d.png)

**Comment by paullallier** [comment]
You're right - that difference wasn't clear.  There's still a related issue though, I think.  

On a rooted machine where I don't meet the hacking level, hack, grow and weaken all fail from the command line with an appropriate error.  However, weaken and grow both work from scripts (on the machine and from another machine).  Hack fails from a script.

I assume the scripted grow and weaken behaviour is not as intended?

<img width="1182" alt="Screenshot 2021-12-22 at 21 10 44" src="https://user-images.githubusercontent.com/42591123/147156581-b675490b-8ef4-469b-af43-14fafa19129f.png">
