### ISSUE TITLE
Bug: Script editor erroneously reports `RAM: Import error`

### ISSUE THREAD

**Issue by aaronransley** [danielyxie/bitburner#2142]
To replicate:

* Create two NS2 scripts on your home device
* Ensure one script imports a function from another
* Connect to another server, e.g. `connect n00dles`
* Open the script editor, focus the script that is importing the other
* `RAM: Import error` message appears at bottom of the script editor

Seems to me that the import validation logic is assuming the server you're currently connected to (via the terminal) is where the script resides, which isn't always the case.

![bitburner_3AWFH9HW0a](https://user-images.githubusercontent.com/5669055/147159599-2c2ffda1-5285-4e1e-9edd-bd19470de2fb.png)

**Comment by mew-slalom-keller** [comment]
The imports are for the 'local' file system, when you connect to a server, you are in that server's file system and do not have access to scripts in 'home'. 

You can push your scripts to the server you're connecting to with: `help scp` will guide you.

**Comment by hydroflame** [comment]
Imports all have to be absolute.

**Comment by aaronransley** [comment]
@mew-slalom-keller I'm aware that scripts don't reside on remote servers unless your `scp` them over. This is a bug regarding an open script editor pointing to a script residing on the `home` device when being connected to another hostname.

@hydroflame I'm not sure I follow here. There doesn't seem to be any issue with my scripts executing properly when using relative imports, and [the documentation](https://bitburner.readthedocs.io/en/latest/netscript/netscriptmisc.html#importing-functions) doesn't mention absolute pathing (and actually seems to use relative pathing).

Just to reiterate, this only occurs when viewing a script that resides on another device when connected to a different hostname / server. Seems like a bug with whatever logic is validating `import` calls?

**Comment by umbravi** [comment]
It seems the script editor assumes open scripts are in the same location as the terminal.

**Comment by aaronransley** [comment]
@hydroflame [This appears to be](https://github.com/danielyxie/bitburner/blob/26106fa71d885c318227198d4194412aa16f3049/src/ScriptEditor/ui/ScriptEditorRoot.tsx#L245) where the bug originates. 

I'm not familiar enough with the codebase, but my gut tells me it would be a huge lift to rework the script editor so that it doesn't assume it's operating on remote files? I'll leave it up to you from here.

**Comment by Chrisch3n** [comment]
I have noticed the same problem and found this bug report because of it. 
Even though I'm even less qualified to suggest a useful solution, I looked into it, to learn a something:  

The [calculateRamUsage Function](https://github.com/danielyxie/bitburner/blob/26106fa71d885c318227198d4194412aa16f3049/src/Script/RamCalculations.ts#L376) requires the script location instead of the player location, to avoid this kind of error.

Would it be possible, to use "scriptEditorCurrentScript.hostname.scripts" (or something in that direction, referencing the [OpenScript-Class](https://github.com/danielyxie/bitburner/blob/26106fa71d885c318227198d4194412aa16f3049/src/ScriptEditor/ui/ScriptEditorRoot.tsx#L80) of the script) instead of  "props.player.getCurrentServer().scripts" for [this ](https://github.com/danielyxie/bitburner/blob/26106fa71d885c318227198d4194412aa16f3049/src/ScriptEditor/ui/ScriptEditorRoot.tsx#L245) request?
