### ISSUE TITLE
portHandle.data appears to be undefined

### ISSUE THREAD

**Issue by Cyprex** [danielyxie/bitburner#2201]
I cannot seem to access a ports underlying array like the documentation suggests.
This script causes a runtimeError:
Error: 
```
myPort.data is undefined
stack:
main@tmp.js:6:2
```
```
/** @param {NS} ns **/
export async function main(ns) {
	let myPort = ns.getPortHandle(1);
	if(myPort.empty()) return;
	ns.tprint("not empty");
	back = myPort.data.pop(); //Get and remove last element in port
	ns.tprint(back);
}
```

NetScriptPort.data seems to be defined here: https://github.com/danielyxie/bitburner/blob/dev/src/NetscriptPort.ts#L14

**Comment by Hedrauta** [comment]
🤔 looked into sourcefile.... there's no `.data`
\>\>
```ts
export interface IPort {
  write: (value: any) => any;
  tryWrite: (value: any) => boolean;
  read: () => any;
  peek: () => any;
  full: () => boolean;
  empty: () => boolean;
  clear: () => void;
}
```

**Comment by ErzengelLichtes** [comment]
`data` is an implementation detail. That's why it's not in the interface. It's emulating a port on a computer, so it's a queue implementation. You can't seek the queue, just as you can't seek a port, you can only read what's at the front. 

Use `read` or `peek`. If you need the whole array, just keep reading and then write the values back to the port.
