### ISSUE TITLE
[bug] nwo - IT job promotion tooltip incorrect

### ISSUE THREAD

**Issue by jtlearner** [danielyxie/bitburner#2236]
In faction NWO, I have reached the position of Head of Engineering.
The tooltip for promotion gives me an erroneous requirement. After clicking, the correct requirement shows up.

This is demonstrated in the attached pictures:
![bug2](https://user-images.githubusercontent.com/88917121/147735941-7af17543-f8da-4738-98eb-e65a9b79630a.jpg)
![bug3](https://user-images.githubusercontent.com/88917121/147735946-65dc9d0d-b64c-44b9-ad98-9ae7de9f1636.jpg)

**Comment by PriNT2357** [comment]
I just encountered the same behavior. This looks to be due to the transition from the `ITCompanyPositions` track to the `SoftwareCompanyPositions` track which is taking place in [CompanyPositionsMetadata.ts](https://github.com/danielyxie/bitburner/blob/3e7a9ac8960ba8424856c1b46fb9e9a79c03b35d/src/Company/data/CompanyPositionsMetadata.ts#L144). Since the current position is no longer in the IT track, the tooltip reverts to the first entry for that track.
If you hover over the `Apply for Software Job`, you will see the requirements match what is displayed in the second screenshot.
It is definitely confusing to have the tooltip revert to the entry level job when the tracks are merging together like this.

**Comment by PriNT2357** [comment]
I dug a bit further into this and found that the logic in [getNextCompanyPosition](https://github.com/danielyxie/bitburner/blob/3e7a9ac8960ba8424856c1b46fb9e9a79c03b35d/src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx#L1805) checks to see if the current position type matches the entry position type. Since the current position of [Head of Engineering](https://github.com/danielyxie/bitburner/blob/3e7a9ac8960ba8424856c1b46fb9e9a79c03b35d/src/Company/data/companypositionnames.ts#L9) is not considered an IT type according to [isITJob()](https://github.com/danielyxie/bitburner/blob/3e7a9ac8960ba8424856c1b46fb9e9a79c03b35d/src/Company/CompanyPosition.ts#L156) the getNextCompanyPosition function returns the entry level position values.

**Comment by phyzical** [comment]
hmm looking a the source it looks like the button uses [getNextCompanyPositionHelper](https://github.com/danielyxie/bitburner/blob/dev/src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx#L1742) will add a pr to use this helper instead

**Comment by Korundur** [comment]
Encountered this today with OmniTek. Makes sense that it goes to the Software Job track, buy maybe tooltip should say something like "Apply for further promotions in Software" starting _before_ you get promoted to Head of Engineering so players know where to go and understand the track change.

**Comment by hydroflame** [comment]
dup
