### ISSUE TITLE
File edited "*" marker does not disapear on save

### ISSUE THREAD

**Issue by Hpcrusher** [danielyxie/bitburner#2290]
When i edit a file in the editor, the title gains a * marker for being edited.
When i save the file with Ctrl + s or with the UI button it does not disappear.
Only when i change the tabs or when i leave the editor and come back it is gone.
It also disappears when i type something in the editor and reappears shortly afterwards.

**Comment by SirGouki** [comment]
Can confirm this is happening on mine as well.  It only goes away if I hit Ctrl + b to close the file or switch using the menu.

**Comment by adalius** [comment]
Same.

**Comment by Kebap** [comment]
Not sure if related or new issue, but clicking the "save file" button or pressing "ctrl + s" brings a "game saved" toast instead:

![image](https://user-images.githubusercontent.com/117238/148091181-e302d5a5-f9e2-41cd-8e9a-021d5df0e04d.png)

**Comment by jNullj** [comment]
I noticed that if you switch tabs the `*` (astrix) disappears.

**Comment by jNullj** [comment]
> Not sure if related or new issue, but clicking the "save file" button or pressing "ctrl + s" brings a "game saved" toast instead:
> 
> ![image](https://user-images.githubusercontent.com/117238/148091181-e302d5a5-f9e2-41cd-8e9a-021d5df0e04d.png)

this seems to be intended depening on your settings as shown ([here](    if (Settings.SaveGameOnFileSave) saveObject.saveGame();))
```javascript
if (Settings.SaveGameOnFileSave) saveObject.saveGame();
```

**Comment by SirGouki** [comment]
Game saving when saving a file is not a bug, as jNullj posted, `Settings.SaveGameOnFileSave` is checking for this Boolean: 
![image](https://user-images.githubusercontent.com/11664236/148474460-806cb333-449c-4c6b-a13a-cd529c96f24d.png)

when checking something that is already boolean, you do not need an expression, just the boolean value (as if evidenced by the code).  Also, you shouldn't be hijacking a bug report with a different bug, especially if you don't *know* it's a bug (and in this case it isn't).

Even if it was, its completely unrelated to the * not being updated on a file save, since this option has been in the game since before Save and Close were split into 2 seperate buttons, and its how the game has behaved since I started playing it a little over a week ago, and the game out right tells you it will happen if you don't turn off the setting.
