### ISSUE TITLE
Casino Roulette Seems Broken

### ISSUE THREAD

**Issue by Marthgun** [danielyxie/bitburner#2382]
I have tested this multiple times and it appears all over the place. If I bet 1-12, I'll win when it is 24B, if I go black, i'll lose when it shows 13B, etc, etc. seems borked

edit: reading the code it looks like the CPU does "cheat" but I would expect to not be cheated in such a ridiculous manner. First of all, if it comes up 24B and I choose 1-12 , I shouldn't be winning. Everything in the code looks fine to me except the cheating section. I'm just not sure how that affects the game or why it would make me win when I should lose. idk if there's a disconnect between the result and the display, if there is I can't see how by my cursory reading of the code.

**Comment by jamie-mac** [comment]
the cheating section was fine (although unfair ;). It just means that 10% of the time, a win will be converted to a loss (but you as the user will never know, as it will move to a number that doesn't win before it shows the result).

The bug was that it uses the previous option you chose instead of the current one. So if you select black for a round, and then select red, if black comes in, you will win because you selected it on the previous guess.
