### ISSUE TITLE
Working-for-companies mechanic has poor UI and documentation

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2394]
The gameplay mechanic whereby you can work for a company & get promoted is almost entirely undocumented and has a non-discoverable, unclear GUI:

- The fact that you can get a promoted by applying for the job you already have is not obvious and not explained anywhere
- The fact that there even *is* a career ladder to advance up is not immediately obvious
- Hovering over one of the job application buttons tells you the minimum stat requirements for that job (or, of you already have a job on that career track, for the next promotion level). However, if the player already meets the stat requirements for a more senior position in that same career track, they will skip directly to the most-senior position they qualify for. Nothing in the UI tells you this is going to happen, or even notifies you that it *has* happened when it does.
- The career tracks are not documented anywhere. ('So, I'm a Senior Software Engineer now? How many more steps does that mean I have to make CTO?')
- Nothing explains what player stats the different career tracks depend on when calculating reputation gain and salary (so that the user can pick the one most in line with their current build)
- There's a quit button, but no explanation of why you might need it. You can hold jobs at multiple companies at once, there's no obligation involved in holding a job (e.g. you aren't forced to work a shift every day), and if you do quit you can reapply and get your job back instantly at, AFAICT, no penalty. The only purpose I can maybe see for it is leaving the CIA or NSA so you can join one of the criminal factions?
  - I think it would be more interesting if you *couldn't* join a criminal faction after being employed by one of the agencies, and conversely could not join the agencies if you're part of those factions; if you wish to switch, you must wait until the next reset. Currently, the only mutually-exclusive choice is which city-based faction to join on each reset.

**Comment by Kebap** [comment]
Small improvements for point 1 and 2 maybe change button from "Apply for X" to "Promote in X" if you already hold that title and there is a promotion available (no matter if you fulfill the criteria yet) so players actually are shown a difference and can find more info with mouse-over.

**Comment by devnuhl** [comment]
Related to hovering and having information with a mouse-over, I just encountered the mouse-over information being irrelevant to my current position / next promotion. I know my current position because it's at the top.
<img width="251" alt="Screenshot 2022-10-03 161952" src="https://user-images.githubusercontent.com/1120006/193697009-c1ee0df3-6067-4bda-9b17-df9996e75003.png">

The hover shows the basic position info, which it has not shown for the last several promotions, but the correct values. Attempting the promotion, though, says I'm ineligible because I lack the stats/rep I need. I'm guessing the tooltips may have been copy/pasted, and this one missed getting updated to the appropriate numbers?

<img width="445" alt="Screenshot 2022-10-03 162008" src="https://user-images.githubusercontent.com/1120006/193697190-82805f12-6857-47c5-b769-f3bb5a2e482c.png">
