### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SloopLiztmin** [danielyxie/bitburner#240]
Caught an exception: TypeError: ActiveScriptsUI[hostname] is undefined

Filename: https://danielyxie.github.io/bitburner/dist/engine.bundle.js

Line Number: 55067

This is a bug, please report to game developer with this message as well as details about how to reproduce the bug.

If you want to be safe, I suggest refreshing the game WITHOUT saving so that your safe doesn't get corrupted

This happens when I run this script

target = args[0];
while(true){
    if(getServerSecurityLevel(target) > getServerMinSecurityLevel(target)){
       weaken(target);
       continue;
    }if(getServerMoneyAvailable(target) < getServerMaxMoney(target)){
        grow(target);
        continue;
    }else{
        hack(target);
    }
}

with these arguments

run slaveS.script -t 200 foodnstuff

After installing augments

**Comment by danielyxie** [comment]
Several questions:

1. Approximately how much time passed between installing Augments and then running that script?
2. Approximately how many scripts were you running before installing Augments?

**Comment by SloopLiztmin** [comment]
I immediately did this script after augmenting
I had around 10 scripts running (All of which were this one, just for farming harakiri-sushi)

**Comment by rharvest** [comment]
I've just had the self-same bug.

1. Just over one day real-time since last augmentation, according to Stats.
2. Unsure as that was a day ago, although probably the same number as below.

In my case I was running about 20-25 scripts on home at the time it threw the error, and one script on most of the other default servers (i.e. I hadn't purchased any extras). I believe I was idling on the active scripts screen, with my home server list toggled open and the rest of the servers closed. New instances of scripts are constantly being spawned on both my home server and the world servers.

**Comment by danielyxie** [comment]
I believe I fixed it. If after reloading the game you still receive the error, let me know
