### ISSUE TITLE
Reexported Scripts Causing "Invalid relative URL or base scheme isn't  hierarchical" Error After Today's Patch

### ISSUE THREAD

**Issue by Reithan** [danielyxie/bitburner#2497]
I have a file `/contracts/Solvers.ns` that I've been using to capture all the Solvers I have written so my contract solving script has access to them. The content of this file is below and has been working for several days:
```
export * as AlgorithmicStockTraderI from "/contracts/AlgorithmicStockTraderI.ns"
export * as AlgorithmicStockTraderII from "/contracts/AlgorithmicStockTraderII.ns"
export * as ArrayJumpingGame from "/contracts/ArrayJumpingGame.ns"
export * as FindLargestPrimeFactor from "/contracts/FindLargestPrimeFactor.ns"
export * as GenerateIPAddresses from "/contracts/GenerateIPAddresses.ns"
export * as TotalWaystoSum from "/contracts/TotalWaystoSum.ns"
export * as UniquePathsinaGridI from "/contracts/UniquePathsinaGridI.ns"
export * as UniquePathsinaGridII from "/contracts/UniquePathsinaGridII.ns"
```

After today's patch, anything including this files fails with this error:
```
RUNTIME ERROR
test.ns@home

Failed to resolve module specifier "/contracts/AlgorithmicStockTraderI.ns". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/contracts/AlgorithmicStockTraderI.ns". Invalid relative url or base scheme isn't hierarchical.
```

Changing each re-export line to something like the below resolves the issue, though
`import * as AlgorithmicStockTraderI from "/contracts/AlgorithmicStockTraderI.ns"; export { AlgorithmicStockTraderI}`

**Comment by neurogenesis** [comment]
@hydroflame : I might have run into another edge case for this. I'm pushing files from VS Code via API server, writing source in TypeScript.

A simple example where:
- "/scripts" contains all scripts
- "/lib" contains helper functions that are imported by scripts

Moving the autocomplete function into it's own module for import/export & re-use:

/lib/autocomplete.ts
```
export function autocomplete(data: any, args: string[]): string[] {
    return data.servers;
}
```

/scripts/simple-test.ts
```
import { NS } from '@ns';
export async function main(ns: NS) {
    const target:any = ns.args[0];
    ns.tprint(target);
}

import { autocomplete } from '/lib/autocomplete';
export { autocomplete };
```

Strangely, this works on the `home` server. I couldn't get the re-export syntax working, but the above seemed to work. But when I run this on a non-home server, I get the above `Invalid relative ...` error.

Looks like the file extension /must/ be specified, but somehow it partially works on the home server. Adding the extension from the above example works on a non-home server, like the following:

Note explicit `*.js` ...
```
import { autocomplete } from '/lib/autocomplete.js';
export { autocomplete };
```

I later realized this is why the normal re-export form wasn't working (due to missing extension). Once fixed, it works fine locally and remotely:
```
export { autocomplete } from '/lib/autocomplete.js';
```

I only mention it for consistent behavior for home / non-home. Not sure if there's a way to enforce the explicit `*.js` for home, as that would ensure both work correctly (as well as ensure both re-export works on home and import works remotely).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#importing_modules_using_import_maps
https://nodejs.org/api/esm.html#esm_import_expressions

❤️    Bitburner makes learning TypeScript immensely more fun than expected, and a great refresher for algorithms too. I really hope Bitburner sparks a new game genre for software engineers and education (public / private / corporate). Security courses are in serious demand...
