### ISSUE TITLE
Unhandled player-written promise reject results in bug message

### ISSUE THREAD

**Issue by quyteriyaki** [danielyxie/bitburner#2546]
**Description:** Unhandled promise reject with return value other than string results in a "Script runtime error. This is a bug please contact game developer"

**Steps to reproduce:**
```javascript
import { NS } from '@ns'

export async function main(ns: NS): Promise<void> {
  await new Promise<string>((resolve, reject) => {
    reject(400)
  })
}
```

**Expected:** The game notifies the location of the exception, something like ("You've written something that causes an exception, did you remember to handle it?") or the game outputs the message of the exception.
**Actual:** The game shows the the bug error with no meaningful response and the script hangs.

**Suggested solution:**
1. Inform the user to handle the exception themselves given that the exception is raised within a player-written script.
2. Inform the user of the value being passed through the exception. This would be in line with the behaviour presented upon passing a string to the exception.

**Comment by phyzical** [comment]
i couldn't run the provided script verbaitum, if i run the following it get told an unexpected error occurs. (presumably because resolve is never called), if i add a resolve instead of reject things work.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/5182053/153749959-e75ea50b-d1e8-4cee-880a-00b5721a777e.png">

```
export async function main(ns) {
  await new Promise((resolve, reject) => {
    reject(400)
  })
}
```

so the question is,
*  is this supported to
*  if so why doesn't it work.
