### ISSUE TITLE
Sleeve Documentation does not match code when buying a sleeve.

### ISSUE THREAD

**Issue by deathly809** [danielyxie/bitburner#2597]
The [docs](https://bitburner.readthedocs.io/en/latest/advancedgameplay/sleeves.html) stat that you need to be on BitNode10 or higher,

```
Purchase Duplicate Sleeves from the faction The Covenant. This is only available in BitNodes-10 and above, and is only available after defeating BitNode-10 at least once. Sleeves purchased this way are permanent (they persist through BitNodes). You can purchase up to 5 Duplicate Sleeves from The Covenant.
```

However, the code only allows on exactly BitNode-10,

FactionRoot.ts
```ts
  const canPurchaseSleeves = faction.name === "The Covenant" && p.bitNodeN === 10;
```

PlayerObjectGeneralMethods.ts
```ts
export function canAccessResleeving(this: IPlayer): boolean {
  return this.bitNodeN === 10 || SourceFileFlags[10] > 0;
}
```

Sleeve.ts
```ts
  const checkSleeveAPIAccess = function (func: any): void {
    if (player.bitNodeN !== 10 && !SourceFileFlags[10]) {
      throw helper.makeRuntimeErrorMsg(
        `sleeve.${func}`,
        "You do not currently have access to the Sleeve API. This is either because you are not in BitNode-10 or because you do not have Source-File 10",
      );
    }
  };
```

**Comment by JoshuaFrancis65** [comment]
The wiki (docs you're referring to) is not very up-to-date, though by what I understand the code here is correct. Current functionality only allows you to purchase new Duplicate Sleeves _while in_ BitNode10, which is why that const in FactionRoot.ts uses p.bitNodeN rather than the value that holds your progression in it.

That comment in Sleeve.ts further pushes this, stating the issue could be that you are not in BitNode-10 or you don't have Source-File 10. As far as I have seen it discussed in the Discord, this is the intended behavior.

**Comment by zeddrak** [comment]
It looks like this has been addressed and the wiki corrected (a ctrl-f for "or higher" returned no results, nor did a quick visual inspection).
Please confirm and close?

**Comment by deathly809** [comment]
Docs have been updated to clarify.  Closing.
