### ISSUE TITLE
Autocompletion fails for second value passed to a flag

### ISSUE THREAD

**Issue by Juxtaposedwords** [danielyxie/bitburner#2617]
When using autocomplete for values passed to flags, only the first value autocomplete works

##  Expected:
Each return statement aligns with the flag declared.

## Observed:
The first autocomplete is used for all flag value inputs

## Example:
```
export function autocomplete(data, args) {
	data.flags([
		["ports", "open"], // whether to use servers which have open prots or not
		["sort_by", "moneyAvailable"], // what to sort entries by
	]);
	return ["open", "closed"]; // whether to use open ports or not
	return ["hostname", "hackLevel", "securityLevel", "moneyAvailable", "maxMoney"]; // Autocomplete servers and scripts
}
```

When running this script, we would see autocomplete for all values to flags is only "open" or "closed"  (whether using the ports flag or sort_by).

**Comment by heap-underflow** [comment]
Anything after that first return line will never get executed, so it's not entirely clear how the second `return` statement should work, but maybe you want something like the following:

```js
    data.flags([
        ["ports", "open"], // whether to use servers which have open prots or not
        ["sort_by", "moneyAvailable"], // what to sort entries by
    ])

    const options = {
        'ports':   ["open", "closed"],
        'sort_by': ["hostname", "hackLevel", "securityLevel", "moneyAvailable", "maxMoney"]
    }

    for(let arg of args.slice(-2)){
        if(arg.startsWith('--')){
            return options[arg.slice(2)]||[]
        }
    }
    return []
```
which autocompletes the appropriate options when preceded by a double-dashed flag.  Note that because of things out of your control, you have to type at least a single letter to get the "double-tab" suggestion popup, but if you do (e.g. `--sort_by h`), you'll see
![image](https://user-images.githubusercontent.com/97357465/149430175-6e3a4249-a236-4c81-86ce-9c8a90a44f24.png)

**Comment by Juxtaposedwords** [comment]
Ah! The second return comes from my misreading of: 
https://bitburner.readthedocs.io/en/latest/netscript/advancedfunctions/autocomplete.html Which I read to mean the first order of args to be autocompleted (as opposed to being three separate examples).


That example is precisely what i'm looking for, thanks!.

**Comment by uhhhclem** [comment]
That doesn't seem to be how autocomplete works, unfortunately.  It returns an array, and if the arg you're typing matches any elements in the array, it will use those elements to autocomplete.

The simplest way to get this to work:
```
export function autocomplete(data, args) {
	return data.servers.map(x => `--target=`+x).concat(fields.map(x => '--sort_by='+x))
}
```
The array returned by the function literally contains all values you could type as flag settings.

If you do this, it will auto-complete the flag name (i.e. `run foo --ta\t` becomes `run foo --target=`).  It can do this because all of the elements in the array that begin with `--ta` also begin with `--target=`.  If you hit TAB again, it will pop up a message listing `--target=home, --target=ecorp...` and so on.  If you type `ap` before you hit TAB, it'll autocomplete to `--target=applied-energetics`, since that's the only element in the autocomplete list that begins with `--target=ap`.

I couldn't get heap-underflow's suggestion to produce any results.
