### ISSUE TITLE
hackAnalyzeThreads results always in infinite on various servers V1.3.0

### ISSUE THREAD

**Issue by Unkn0wnNPC** [danielyxie/bitburner#2628]
Just run the script below and it'll always result in Infinite on various servers

`export async function main(ns) {
 let destinations = ns.read("/hackV2/servers-sorted.txt");
 destinations = JSON.parse(destinations);
 let test = ns.hackAnalyzeThreads("foodnstuff", 1)
 ns.print(test)
}`

![bitburner_Issue](https://user-images.githubusercontent.com/71597557/149597087-1d7604f8-f570-48ec-8d8a-556d945f91b6.jpg)
[bitburnerSave_1642201801_BN1x0.json.txt](https://github.com/danielyxie/bitburner/files/7873742/bitburnerSave_1642201801_BN1x0.json.txt)

**Comment by nickinitro** [comment]
can confirm!

**Comment by Felix-Dziatkowski** [comment]
i've the exact same issue :(

**Comment by geiloschefos** [comment]
same...

**Comment by zeddrak** [comment]
Are you in a bitnode with a BitNodeMultipliers.ScriptHackMoney == 0?
If so, this would be the correct response (no amount of threads will allow you to steal any money)

Similarly having a server security of 100+ should result in infinity.

**Comment by zeddrak** [comment]
Hmm...
I guess that if BitNodeMultipliers.ScriptHackMoney could be < 0, then moving it before the check could result in a difference behavior, but that'd still be really weird, as the previous version would've ended up in negative threads being needed before.

**Comment by zeddrak** [comment]
Update, I am working on a fix for this in my scripts. Once I've completed and tested there, I will check with Hydroflame if he wants them imported into the source game. It is a complicated problem though (since the amount grown is now partially based on the threads used, making getting the threads needed a self-referential nightmare akin to determining how much rocket fuel you need to get into orbit...)

**Comment by zeddrak** [comment]
[My Discord discussion in developement](https://discord.com/channels/415207508303544321/459097632896188436/934590171066802187)

> Ok, concerning the growAnalyze, I have a couple of options to deal with the infinity issues:
> https://github.com/danielyxie/bitburner/issues/2635
> https://github.com/danielyxie/bitburner/issues/2628
> 
> Option 1) Just retun Math.min(growAnalyze normal value, server.moneyMax) --- this basically assumes a minimum of $1 server and ignores the extra power added to grow ($1/thread) and so will return larger values than actually needed (potentially MANY times larger in some case. Theoretical example: if it takes 100 threads to double - grow x2 - a certain server with moneyMax of $200, then 100 threads is all that would be needed to grow it to max from $0, but this naïve solution is returning 200)
> 
> Option 2) Is basically to use a first order differential equation - ie, how many threads it takes is dependent on how many threads you need... I'll look up one of the approximation techniques for that kind of first order differential equation and use that (most approach very quickly, and we only need to get to an error <1 since integer threads anyways). This has the added advantage of taking into consideration the extra grow power for non-full grows as well.
> 
> Opinions?
> (Follow-up: If we go with option 1, should I also change the previously discussed functions to behave accordingly - eliminating the infinity thing entirely? Basically, this would change the mechanic for growing <$1 servers to assume $1, instead of $1/thread, consistently.)

**Comment by phyzical** [comment]
i'm personally not a fan of having an equation
Mostly because a complicated algorithm to stop this issue will break one day, not if just when 😆

The other way to look at this would be to fix the issue on the other side, anywhere the result could be `Infinity`make it invalid. 
though i dont like this one because Infinity will eventually be a valid result due to the cap on number in JS land
So we  would have to consider to use a number system similar to other idle games where they use letters for additional categorizing of large numbers. but we just have no reason for numbers to get bigger than the js cap at this time

imho, just make the minimum 0.00000000001 (or 1).

But its a question for higher powers
