### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by kopelli** [danielyxie/bitburner#265]
@danielyxie What sort of usage numbers are you seeing in Google Analytics? There's a number of code improvements that *should* work across newer browsers, but if people are still playing this in Internet Explorer there might be some problems (like the use of the spread operator in the NetScript 2.0 source). And looking through the CSS, there's some tricks/hacks in there that could be streamlined if certain browsers aren't regularly used.

**Comment by danielyxie** [comment]
It's mostly Chrome/Firefox but there is a small percentage (~3%) that uses Internet Explorer/Opera

**Comment by kopelli** [comment]
Good to know. Do you feel it would be worth hooking up a transpiler into the WebPack process to target ES5 for the Internet Explorer users, or add some sort of "Not Supported" message for them so newer EcmaScript syntax can be used?

**Comment by kopelli** [comment]
I was thinking something like BabelJS to have the engine.bundle.js being ES5 across the board. Wouldn't be all that different from introducing TypeScript and having everything transpile to ES5.

But along a similar thought thread, it would be nice to update the HTML/CSS to leverage something like CSS Grid or Flexbox. That way some things could be laid out more uniformly than basing it on percentage of the screen. But that definitely doesn't have a nice fallback option... 😞

**Comment by jjspace** [comment]
@danielyxie if you're ok with dropping support for IE then many new features will be opened up to you. Personally I think it's a really good idea because there are so few people who still use IE and this is a more specialized application (as opposed to in info site or something that all computers/old systems should be able to access). You can see global usage stats [here](https://caniuse.com/usage-table). Also by giving up IE you're still not loosing the percentage of users that use the "default" browser on Windows because any relatively new Windows system has moved to Edge which does [fully](https://kangax.github.io/compat-table/es6/) support all ES6 features that modern browsers to.

Also by ditching IE the amount of css capabilities that open up to use is great. Newer CSS is very powerful and can make many things easier. As @kopelli mentioned, CSS Grid and Flexbox can greatly help with pages that position elements the way that bitburner does. Regardless what you decide I'd recommend implementing Flexbox because it now has ["full"](https://caniuse.com/#search=flexbox) browser support but if you're willing to drop Opera too then you should look into [Grid](https://caniuse.com/#search=grid) as well. (I'm more than happy to help you revamp the css if you need/want)

**Comment by danielyxie** [comment]
I am okay with dropping IE (and Opera)
