### ISSUE TITLE
Incorrect parameters for ns.spawn()

### ISSUE THREAD

**Issue by hi117** [danielyxie/bitburner#2690]
On git version of documentaiton, the documentation says that ns.spawn()'s args parameter is a `string[]`. In actuality its a `string...`.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by Master-Guy** [comment]
![image](https://user-images.githubusercontent.com/566429/159133398-f9fa0508-7ce4-44bc-9c35-0f91e267bf6b.png)

It might be a bit confusing, but it does say `...args`.
Unfortunately we cannot change this AFAIK due to TypeScript restrictions.

![image](https://user-images.githubusercontent.com/566429/159133421-f3aa2750-b39d-4810-9ce1-e5df44da7142.png)

**Comment by Ornedan** [comment]
`...` in last parameter of a function means it's a variadic function. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

Any parameters the caller gives, starting from the `...param`'s position are gathered into an array for the function code to access.

However, it is the case that `spawn`'s argument list is described wrong, the last parameter type should be `Array<string | number | boolean>`, matching `exec`.
