### ISSUE TITLE
Coding contract window lost due to singularity function

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2698]
I had a coding contract window open when a script I had running in the background called the exercise-at-gym singularity function. This caused the game to switch to the gym training screen and the contract window to vanish. When I went back to the terminal and tried to reopen the contract by running it again, I got an error message saying "There's already a Coding Contract in Progress". I had to reload the game to get the contract open again.

Version: Bitburner v1.3.0 (9fdc3ac5)

**Comment by SagePtr** [comment]
Also contract window disappears when you return your focus to faction job (hacking contracts for instance) when coding contract window is opened. You cannot programmatically solve contracts after this (the game thinks contract is running) until you reload the game.

**Comment by nulflux** [comment]
This also happens when triggering a DOM click() on a menu option like City as the contract window is open. The coding contract is forever in progress and there is no way to return to it. There are two potential solutions for this: 1) instead of an error the run command could default cancel and re-open the contract or 2) make available a command to cancel the current contract. Solution 1 solves the problem universally; solution 2 allows the users to solve the problem themselves. Since there is no special mechanic preventing players pre-singularity from running a coding contract programmatically I don't believe it should be a singularity function but rather a function available by default.

**Comment by macdjord** [comment]
@phyzical The problem isn't that the window closes. The problem is you can't reopen it because the game thinks its still open.

**Comment by BrianLDev** [comment]
This bug happened to me today too in the way @SagePtr described.

If you have a contract open and change focus to Faction work, the coding contract UI disappears but the game incorrectly thinks that it's still open.  Doesn't look like there's a way to get the UI to pop back up again, and trying to run the contract again gives an error message. `There's already a Coding Contract in Progress`.  The only way to fix it is to close and reopen the game.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/16980550/154361545-78437e85-7198-4358-9863-6d588d21583e.png">

**Comment by BrianLDev** [comment]
So I'm guessing the fix would be in the code that handles focus.  It should check for any open coding contracts and simply close them before changing focus.

**Comment by macdjord** [comment]
@BrianLDev That seems like treating the symptom rather than the problem to me. A better solution would be to change the 'is a coding contract in progress' check so it actually checks whether there is a contract window open - as in, examine the DOM - rather than depend on finding every possible way that the contract window could get closed and ensuring each one marks the window as closed first.

**Comment by holgero** [comment]
Why is there a guard against opening the contract again, anyway? Perhaps just delete that?

**Comment by rayanth** [comment]
@holgero it was likely intended in order to prevent two _different_ coding contracts from being opened at the same time. I agree with @macdjord that the better fix would be in the check for a coding contract in progress, but rather than simply check if a window is open, check if a _different_ contract's window is open. If the same coding contract's window is thought to be open, just display it again.
