### ISSUE TITLE
Expressions for setting material quantity not working anymore

### ISSUE THREAD

**Issue by ltoni90** [danielyxie/bitburner#2719]
**Game Version**: v.1.4.0
**Source File**: [Corporations/Actions.ts](https://github.com/danielyxie/bitburner/blob/dev/src/Corporation/Actions.ts)
**Line Number**: 120
**OS**: Windows 10
**Description**:
Before v1.4.0 it was possible to use expressions like 'PROD-300'. This does not work anymore because of commit [98e8910c3aed719003730acd785d7aa9f1d118b7](https://github.com/danielyxie/bitburner/commit/98e8910c3aed719003730acd785d7aa9f1d118b7#diff-741b7886774b08ffc9963810bfac1e2700943d5effa7a653ff3569e522e538dc). At [line 120 in Actions.ts](https://github.com/danielyxie/bitburner/blob/34f18a6000a1c14ecd1a12712e8a86747a54f02e/src/Corporation/Actions.ts#L120) a new condition `parseFloat(tempQty) < 0` was added and this is causing the exception "Invalid value or expression for sell price field" as the variables MAX and PROD will be both replaced by 1 for a temporary evaluation of the expression. Either remove condition or rewrite logic.

Thank you!

**Comment by ltoni90** [comment]
Hey guys, as this is a game breaking bug for me regarding corporations, I fixed the bug by myself and created a pull request. If something should not be correct, let me know that so I can fix that.
#2757

**Comment by spinear** [comment]
+1 Please fix this or approve his pull request.

**Comment by ChrissiQ** [comment]
This bug is quite game breaking - I am unable to export materials other than MAX.

I have a software division.  I want to keep a certain amount of AI cores in my warehouse because it contributes to the production multiplier.

In my game, in Aevum, MP of AI Cores is $11k, while in Sector-12 it is $52k, so obviously I would like to be able to export this material from Aevum to Sector-12 and sell it in Sector-12.

However, AI Cores contribute to the production multiplier, so I do not want to export or sell MAX - only prod.

I can't export PROD (that would be a great feature!!!), so instead I want to export a number less than prod, say 32, and sell PROD-32.

Since I cannot sell PROD-(amount), this is not possible, so I can't balance my sell and export.

We really need this fix!

**Comment by Penumbra69** [comment]
Just here to leave my +1 support for this bug fix.  As it was my 1st corporation, I thought it was me not understanding the systems, but if I follow the guidance in the pop-up to use "PROD-10" -- it doesn't work, and I cant make it work by trying to use %'s.  Please fix:

My attempt to use it:
![image](https://user-images.githubusercontent.com/17106044/153679584-0b85f091-f91c-4558-92df-1d6895675265.png)

The response:
![image](https://user-images.githubusercontent.com/17106044/153679616-c665f29c-f0a8-4c53-b1af-099ed8f3e786.png)

This is making life very difficult for me to balance my warehouses!


Thanks, 

P
