### ISSUE TITLE
Add hacking level option hack/grow/weaken

### ISSUE THREAD

**Issue by ionori** [danielyxie/bitburner#2754]
Everybody who has tried to make a batch hacking algorithm has probably struggled with timing issues due to leveling up mid-batch. Adding a hack level option (capped at the character's current hacking level) would solve the problem, as the script could note the hack level at the start of the batch and use it for subsequent operations.

I don't know if that problem is part of the intended experience, but I feel like it would make writing batch hacking algorithms a lot more enjoyable if I didn't have to worry about it, since timing problems are really frustrating.

**Comment by zeddrak** [comment]
[formulas.exe](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.hackingformulas.md) is for this purpose (you can modify the player (and server) objects (or even create them from scratch) before handing them to the formulas.

**Comment by zeddrak** [comment]
Oh - or do you mean handing the actual hack call a reduced hack level and have it run at the "less efficient" level?
In which case, yeah, build in a buffer in your timings to allow shrinkage. ;) (ie, use formulas.exe to calculate at a higher skill, then run your cycle. Would this have the same effect you're asking for?)

**Comment by ionori** [comment]
> Oh - or do you mean handing the actual hack call a reduced hack level and have it run at the "less efficient" level? In which case, yeah, build in a buffer in your timings to allow shrinkage. ;) (ie, use formulas.exe to calculate at a higher skill, then run your cycle. Would this have the same effect you're asking for?)

That's what I meant. I've had to bump the buffer from 200ms to 2000ms to accommodate parallel (as in multiple batches of WWGH executing at the same time with an offset) hacking of the same target, and I'm still getting desynced. Given how fast your hacking level can climb and how long some juicier targets can take to weaken (upwards of 20m even with a high hack skill), predicting the hack level I will be at when it's time to run grow and hack is non-trivial to say the least.

Your post has given me an idea to calculate the difference between how long the task was going to run when the timings were computed at the start of the batch and how long it's going to take when it's time to run it, then await the difference before starting the task (probably do it with a while loop in case another hack level increase occurs while waiting).

I feel moderately confident about my ability to implement this new approach, but at the same time I feel like giving the player the ability to run HGW at a specified hacking level would be a good change to make parallel batch hacking possible for a slightly less tiny portion of the playerbase.

Then again, maybe I've missed a simpler solution to parallel batch hacking and the problem isn't as difficult as I believe it to be.

**Comment by macdjord** [comment]
My solution to this is:

- Make the `grow()` command stronger than strictly necessary. I have my script set up so that 2 grows will restore as much money as 3 hacks take, so if 2 hacks go off in a row, we get back to full money in a couple cycles anyway.
- Give your `weaken()` commands a large overkill factor - I use 3 times as many as I need, since they take up such a small portion of the memory footprint in the first place - and split them up into multiple scripts which are spread out throughout the cycle - I use 8 weaken scripts in the early game when my income is limited by memory, then cut that down to 4 in the late-game when the limiting factor is how many total scripts I can run at once before my browser slows down - so that even if the grow and weaken commands don't finish exactly when you expected them to, there's a weaken script along soon enough.
- Recalculate your timings every time your hack levels up.

**Comment by hydroflame** [comment]
Time is calculated at the beginning, effect at the end.

**Comment by ionori** [comment]
> Time is calculated at the beginning, effect at the end.

I know, nothing I said contradicts this. I'm proposing an option for HGW that determines what hack skill it runs at, so I can scheduled a HGW task now to run in the future and expect it to end when I want to, not before because it was executed with a higher hack skill than what I had when I scheduled it.
