### ISSUE TITLE
[BUG] Sleeves - TypeError: Cannot read properties of undefined (reading 'getInfo')

### ISSUE THREAD

**Issue by zeddrak** [danielyxie/bitburner#2832]
### How did this happen?
Best guess is that I had 2 sleeves tasks open to "Work for faction - Daedalus - Field work" (because I realized there was a better choice after opening it up on a random sleeve - but hadn't hit set, so I just opened it on the better one and hit set). Recovery mode was entered the moment I hit the set task button.

Please fill this information with details if relevant.
I don't have Sleeve scripts, so I'm assuming it's not one of my scripts, but just in case,
My scripts can be found here: https://github.com/zeddrak/bitburner-scripts (allinone.js contains all the scripts in one file for easy searching - it's also the only one that's up to date.)

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.4.0 (1e126d40)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Tried to include save here, but it threw an error when I tried to submit it - something about a 65536 character limit,,,
```

**Comment by ShawnPatton** [comment]
Can confirm that it doesn't just happen manually. I just improved my script with auto-assigning to multiple factions. It was foolproof enough to run 4 hours with no problem, but seems to hit this issue very regularly if I'm on the Sleeves page when it's reassigning them back and forth across factions. On a related note, the sleeve.setToFactionWork function returns some flavor of nothing (instead of true or false) when it tries to assign to a faction that another sleeve is already working on. Only caught that one because ns.read hates empty files and would crash the script.

**Comment by ShawnPatton** [comment]
UPDATE: This is not harmless. It appears to cause some form of save corruption on an individual sleeve, breaking any use of getSleevePurchasableAugs on them as well as whatever equivalent the UI uses. The Sleeves tab will not show their purchasable augs, but they can be bought via script if the name is hardcoded or retrieved from somewhere else.
