### ISSUE TITLE
Bladeburner Synthoid Population UI

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2836]
There are several issues with the current bladeburner UI for synthoid population and community counts:

- We are given an estimated synthoid population count and estimated(?) number of synthoid communities for the current city. We're given a number of actions that we're told will improve the accuracy of these estimates, and a skill which will make these actions more effective. However, we're given no feedback for how accurate these estimates are to start with, or how much our actions are improving them.
- There is no way to check the populations of other cities except by switching to them one by one.
- We are given occasional intelligence updates hinting at changes to populations - migrations and such - but these don't update our estimated populations, nor is there any good way to track them over time.

I propose that the UI be changed to display synthoid population and community counts as a chart like so:

| City | Est. Synth. Pop. | Pop. Error | Est. Communities | Coms. Error |
|-|-|-|-|-|
| Sector-12 | 1.2b | +20% / -8% | 123 | +2 / -4 |
| **Aevum** | 1.8b | +1% / -12% | 87 | +5 / -4 |
| Volhaven | 123m | +30% / -30% | 17 | +1 / -0 |

- 'Aevum' is highlighted because its the player's active city
- Every time the player completes an action which improves their estimates, the error boundaries are reduced and the estimates are updated
- When the player gets an intelligence update about a migration, the estimates do not change, but the error bars do, and in the appropriate direction (e.g. if the player is notified about a migration from Sector-12 to Aevum, then the negative error boundary of Sector-12 and the positive error boundary of Aevum increase)

Version: a3c599e6

**Comment by zeddrak** [comment]
> We're given a number of actions that we're told will improve the accuracy of these estimates, and a skill which will make these actions more effective. However, we're given no feedback for how accurate these estimates are to start with, or how much our actions are improving them.
> Every time the player completes an action which improves their estimates, the error boundaries are reduced and the estimates are updated

Isn't that what the range of the error tells you? If the error is +10 / -12, then your estimate isn't very good. Increasing the accuracy should reduce the range of the error, to something more like +5 / -6 (this is an estimate that's twice as accurate as the previous one, for example). So completing those actions means the "estimate" is now more closely bounded to the error range (ie, your estimate is more accurate and the range of error is reduced.).

>We are given occasional intelligence updates hinting at changes to populations - migrations and such - but these don't update our estimated populations, nor is there any good way to track them over time.
> When the player gets an intelligence update about a migration, the estimates do not change, but the error bars do, and in the appropriate direction (e.g. if the player is notified about a migration from Sector-12 to Aevum, then the negative error boundary of Sector-12 and the positive error boundary of Aevum increase)
I'm assuming this is because we don't know how many actually migrated (ie we have an unconfirmed report, so we know what we started with - our unchanged estimations - and we know how many were reported as having moved - our updated error bars - but we haven't confirmed how many actually arrived, nor how many gave up and went back, etc, so our estimates have become less accurate.) Essentially, migrations make estimates less accurate over time (as more migrations occur), while the actions we take make them more accurate - this is the dance (basically, if you do nothing, then the migrations will eventually make the estimates near useless)...

**Comment by macdjord** [comment]
> Isn't that what the range of the error tells you? If the error is +10 / -12, then your estimate isn't very good.

That's the problem - right now, we don't get to *see* the error range. It isn't displayed anywhere.
