### ISSUE TITLE
Warehouse full because of wrong export of "Metal"

### ISSUE THREAD

**Issue by TheCrazyT** [danielyxie/bitburner#2860]
I accidently exported "Metal" to an "Agriculture"-coporation.
Problem is that I can not get it away from storage.
There is no "Metal" entry on the list of the UI to export it back.

So it looks like a bug.
I guess I should not be able to export "Metal" to "Agriculture" anyway (but it was selected by default).

**Comment by ChrissiQ** [comment]
I also have this issue - you can accidentally export Plants/Food from an Ag industry to a Software industry, and then you cannot remove it from your warehouse because the interface for it doesn't exist.

Maybe you can remove it with scripts but I don't have enough RAM yet to run corp scripts (requires 1TB) on my initial run of BN3.  Shouldn't be necessary.
