### ISSUE TITLE
Proposal: Hack synchronization (and underlying issue/bug)

### ISSUE THREAD

**Issue by mricher-git** [danielyxie/bitburner#2887]
I have seen a number of threads/requests related to challenges around syncing batches, ranging from adding a 'hackLvl' parameter to hack(), etc, but I believe the solution is much simpler. 

I'm not sure if the inability to sync "batches" is an intended gameplay mechanic or not, but if not, IMHO, the real issue here is the fact the hack() calculates the time to process at the beginning of the call, but calculates the amount stolen after the command has executed. It not only makes it impossible to sync, it feel unbalanced that the processing time is calculated based on your level at the moment of executing, but the result/amount stolen is based on your level at the time it finishes executing.

Specifically: [NetscriptFunction.ts 346-353](https://github.com/danielyxie/bitburner/blob/9ddb1c43796d2c020655bae1052e8ed67075c9e9/src/NetscriptFunctions.ts#L346-L353)

`percentHacked = calculatePercentMoneyHacked(server, Player);` as well as exp, etc are all computed after the netscriptDelay. The simple solution to all of this is to compute these values before the sleep. In fact the entire ".then" clause could be precomputed but it would only take affect if successful.

Again, IMHO the hack process should begin processing the moment it hack() is executed. The delay is an "under the hood mechanic" to simulate processing time. Because the amount stolen is computed once hack() has finished processing, it makes little sense to me why there are an abundance of Analyze, Time and Formulas functions which provide little benefit if the process doesn't determine it's fate until after it's called, where the player may have up-leveled numerous times during the processing time.

Also note, I don't really want to explain how here as a spoiler, but the current situation is quite exploitable at the moment the way it currently is. This is probably obscure enough such that only people in the know are likely to grasp, but high level, your batch rate is very much a function of hack time, and a longer hack time actually allows for more batches to Q, therefore you can Q up a bunch, meanwhile hammer on a low lever server to crank up your level before the hacks finish executing, and then you will get an inflated amount of money. Therefore, even if not for the proposal on the ability to sync, the delay and amount should be tied together based on hack level and therefore need to be calculated at the same time.

**Comment by phyzical** [comment]
incase i miss understand your suggesting that the hack/grow/weaken should enforce whatever it is they would have applied as if they took 0 seconds to complete correct?

if this is the case imo i agree, you shouldn't be able to exploit the fact that your batches get more (or less) based off whatever has occurred when it finishes.

like if i was to "estimate a hack after x amount of time" i expect that it does that not gives you more because other actions have occurred

but at the same time... it makes sense that it SHOULD give you different values given the actions of your other scripts....

hmmmm

this is why i liked the idea that another person suggest of making batching a valid approach in a new BN and we can workout how to go about that then for that BN but tbh that just throwing these issues under a rug and making it future us's problem 😆

**Comment by mricher-git** [comment]
Yes, currently the code sleeps, then calculates the effect. I'm suggesting hack/grow/weaken should calculate the sleep duration and the effect at the same time (time 0), then sleep for the duration and apply the pre-calculated effect. The sleep duration and the outcome should be computed together. If the duration and the effect are both functions of my hack level, etc, they should be interlinked.

Like I said, the sleep is a mechanic of the game to simulate the duration of applying the effect (hack/weaken/grow), but the effect should start immediately and the outcome should be pre-calculated, otherwise it would be a nightmare of interpolating between the beginning and end of the duration.

Not sure why we need a different BN to make batching a valid approach. Even with this "bug" (I say that as it's also exploitable as I explained earlier), I can still batch like crazy and it only causes a slight issue once in awhile, because the batching method causes your hack level to soar, and once it's very high, the odds of your hack level changing during the course of a command becomes more limited, and the weaken time is so low, even when it does, it fixes itself in under a minute.

**Comment by phyzical** [comment]
nah just a suggestion as to "make batching crappy or redundant for most of the game" "maybe add a bitnode that encourges batching and fix it properly for that" 

yeah all the makes sense and i agree its just as much as it makes sense your hacking and your result should be predetermined it also makes sense that it shouldnt and should be affected by any other batched things that have happened since it started and finished.

i.e you would just be able to hack on 100s of threads and steal 100X max money when in reality the first successful hack could have taken everything

if the suggestion is even deeper and its meant to predetermine how much would get taken and adjust this in some common state you would still have issues where users could time it well enough that a bunch of hacks "precalculate" max money lets be generous and say 5 of them this would give them 5x max money which wouldn't be correct either.
