### ISSUE TITLE
Suggestion: Provide useful info on the Factions screen

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#2890]
The Factions screen only lists the names of the Factions you have joined, so if you want more info (i.e. the reputation values, compare which faction has the highest favor, etc), then you have to do a lot of clicking in and out of each faction.

It would be great if the Faction screen also showed the reputation and favor values for each faction that you've joined.  Might also be nice to show how many augmentations still available to buy (e.g. Augs 4/6).

It would look something like this:

```
FACTION NAME         REPUTATION          FAVOR          AUGS
CyberSec             19.820k             29             1/5
Sector-12            12.864k             41             5/7
```

**Comment by zeddrak** [comment]
Here's the file most likely needing to be modified, but not sure how best to get that extra data into it... (ln 70)
[bitburner/src/Faction/ui/FactionsRoot.tsx /](https://github.com/danielyxie/bitburner/blob/dev/src/Faction/ui/FactionsRoot.tsx)

**Comment by macdjord** [comment]
@BrianLDev I'd also include how many augs are unlocked (i.e. you have enough rep to buy them) and how many are purchasable (you have enough rep & money to buy them now).

**Comment by macdjord** [comment]
Also, it would be useful to be able to sort the page by any of these columns.

**Comment by Chris380** [comment]
I agree that this overview could be improved to reduce tedious clicking. Just fiddled around a bit and came to something like this:
![image](https://user-images.githubusercontent.com/14816381/162761929-822e2aa4-85fa-4479-bb1c-2ef6d373c07d.png)
The faction and reputation values have a tooltip because we don't have column headers.
In my opinion sorting is not that important in most scenarios and the sort buttons might bloat the UI a bit.
