### ISSUE TITLE
Change Stanek.get to 0GB RAM

### ISSUE THREAD

**Issue by trhr** [danielyxie/bitburner#2903]
If you can't fix the regex, just cut the cost. It's a critical bug.

**Comment by phyzical** [comment]
(for some more context) how much ram does it apply atm?

**Comment by dcbishop** [comment]
2GB.

I've been playing around with Rust WASM and it happens on *every* script. Possibly because the WASM has to be base64 encoded and 'get' is basically guaranteed to appear (although I'm surprised the mem analyzer flags it since it's surrounded by other characters). exec also shows up too.

Going to have to look into a way to avoid the memory analyzer.

From discord I got the impression that the plan was to rename stanek.get to something else though.

**Comment by TheMas3212** [comment]
underlying issue is tracked in #2529
