### ISSUE TITLE
Hacknet Servers are incorrectly named "nodes"

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3023]
After beating BN9 (Hacktocracy) and getting upgrade from Hacknet nodes to Hashnet servers, the new servers show up under the name `hacknet-node-x`.  For clarity and consistency, it's better if they're named `hacknet-server-x` since nodes and servers have very different functionality.

![image](https://user-images.githubusercontent.com/16980550/155268088-0bb37feb-fb80-4fb2-99f0-0b2184bc2c78.png)

**Comment by ChrissiQ** [comment]
I'm not sure but this might be a matter of opinion. To me the current naming makes sense because it's a server representing the hacknet node, so the name of the server should match the name of the node as `hacknet-node-i`.  But I'm not sure what others might think.

**Comment by BrianLDev** [comment]
@ChrissiQ The code is **VERY** explicit in differentiating between what is a Hacknet Node and a Hacknet Server.  Nodes and Severs are distinct and have different functionality so it's best to keep the terminology clear.

It was an easy fix anyways, just tweak 1 line of code.  I already submitted a PR to fix it :)
![image](https://user-images.githubusercontent.com/16980550/155271632-f169c36a-3a4e-494d-8580-2500d829bee8.png)

**Comment by ChrissiQ** [comment]
I could be missing something because I have not played this BN - isn't the server created and named after the HN node of the same name?  If so, you're right that they are completely different objects, but I still feel the name is appropriate and does not cause confusion. It's the hacknet server representing the node, so it shares its name, even though it is a server and not a node.  I thought these servers are created based on the nodes which have the name `hacknet-node-i`.

 If I'm wrong about that because I haven't encountered this specific game feature, sorry, ignore me 😆

**Comment by BrianLDev** [comment]
For one quick example, here are the separate and different constant values for Hacknet Nodes vs Hacknet Servers:
![image](https://user-images.githubusercontent.com/16980550/155383642-7c9d334a-d5b6-45e7-9ac5-8ea8a1846b70.png)
![image](https://user-images.githubusercontent.com/16980550/155383791-ecc29c0b-0d76-4858-9d18-56c31d1e28dd.png)

**Comment by BrianLDev** [comment]
since this one is a bit controversial I'll just close out the issue and related PR.

In general, it's still best to avoid inconsistent terminology and also avoid using "magic strings" in scripts, but there are bigger fish to fry at the moment so I'm not going to fight for this change.
