### ISSUE TITLE
Allow moving '.msg' & '.lit' files

### ISSUE THREAD

**Issue by ztimson** [danielyxie/bitburner#3041]
Currently the `mv` command only works with scripts & `.txt` files.

It would be nice if we could also move `.msg` and `.lit` files so that we clean up the home directory as it grows. It might be worth  automatically storing `.msg` files inside a `/mail/` directory by default instead of the home directory.

**Comment by hydroflame** [comment]
This is complicated because all those files are harcoded in the game. So it would need a rather complicated rework to make sure that we don't bloat the save file size while giving the ability to move.

For whoever wants to pick this up.

What needs to happen is that **all** files in the game right now are simply strings. They need to be converted to objects with 2 fields, `name` and `content` where content is the original name of the lit/msg so that we can map back to content.

That means `mv` and `cat` and all that jazz needs to be updated. It's honestly a lot of work for little reward.

**Comment by ztimson** [comment]
Hmm I see... Since updating the way these files work is a pain, could we just save them to a different directory such as `/mail/` & `/docs/`? I would imagine thats much easier and its the end goal of being able to move messages anyways.

**Comment by phyzical** [comment]
thats probably a quick fix, but at the same time is too many files that bad? id assume you've probably got your scripts in folders already. i think just waiting for a proper fix is the correct approach that way if we added other types of files in the future things are easier and this doesnt crop up again

**Comment by ztimson** [comment]
> is too many files that bad? id assume you've probably got your scripts in folders already

Currently my home directory has 12 `.exe`, 6 `.msg` & thats not incuding lit files or my sub directories for configs & scripts. So in my opinion, it is a lot files & I would like to organize more.

> waiting for a proper fix is the correct approach that way if we added other types of files in the future things are easier and this doesnt crop up again

I definitely agree that the files need to be reworked & unified That being said, at least in my opinion, I still think it's worth having the `.msg` files put into a seperate `/mail/` directory by default to help clean things up.
