### ISSUE TITLE
sleeve.setToCompanyWork behaviour different from UI

### ISSUE THREAD

**Issue by halandriel** [danielyxie/bitburner#3132]
You can place all sleeves to work for the same company when placing through the UI. When trying the same through the API, it's only possible to place one sleeve per company:
![Screenshot 2022-03-13 083805](https://user-images.githubusercontent.com/96341316/158050191-1ba2c265-42b2-4bd1-9ff1-8469c324379a.png)
![Screenshot 2022-03-13 083951](https://user-images.githubusercontent.com/96341316/158050195-3d671457-6c50-4681-9d38-b66d064eca5c.png)
![Screenshot 2022-03-13 084043](https://user-images.githubusercontent.com/96341316/158050201-6a5a5fa3-8730-47f1-9c4c-8d8f15776899.png)

Also the error message is wrong.

https://github.com/danielyxie/bitburner/blob/bb433d4629d436ad18baf1338a93d2306a85011f/src/NetscriptFunctions/Sleeve.ts#L82

**Comment by hydroflame** [comment]
Ok so the problem here is that you should never be allowed to set all sleeve to work at the same company.

**Comment by vladtepesch** [comment]
is this really a problem?
In my opinion it somehow fit to the overall logic. 
Factions are some kind of underground organisations where you know each other and it would be obvious if two clones are present at the same time. Otherwise mega corps with millions of indistinguishable workers no one woud notice
