### ISSUE TITLE
Game crash into recovery mode with Could not find Company:  (at "Work")

### ISSUE THREAD

**Issue by Scigrapher** [danielyxie/bitburner#3244]
### How did this happen?

I wish I could be more helpful, but it was running scripts while I was away.  I have no idea what caused it or why.

### Environment

* Error: Error: Could not find Company: 
* Page: Work
* Version: v1.5.0 (b265d7ba)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
[RECOVERY_BITBURNER_1648043863.zip](https://github.com/danielyxie/bitburner/files/8338140/RECOVERY_BITBURNER_1648043863.zip)
```

**Comment by phyzical** [comment]
https://github.com/danielyxie/bitburner/blob/feature%2Fadd-infiltration-faction/src/ui/WorkInProgressRoot.tsx#L222

is whats throwing it, if i was to guess its a similar issue to the one with working for a faction and augmenting at the same time, instead of throwing we should just serve a similar error modal to the faction stuff

```
  if (comp == null || !(comp instanceof Company)) {
      return (
        <>
          <Typography variant="h4" color="primary">
            You cannot work for {player.companyName || "(Company not found)"} at this time,
            please try again if you think this should have worked
          </Typography>
          <Button onClick={() => router.toFactions()}>Back to Factions</Button>
        </>
      );
    }
    ```
