### ISSUE TITLE
Corp share price tanks too dramatically after 1e6 shares sold.

### ISSUE THREAD

**Issue by alainbryden** [danielyxie/bitburner#3322]
See the gif below from selling an increasing number of shares in a corporation.

![bitburner_2022-04-01_11-44-54](https://user-images.githubusercontent.com/2285037/161305566-43f34e2c-9f34-4337-b476-f3a4370e4255.gif)

Notice that the "total sale price" barely increases after 1e6.

This is due to an over-zealous mechanic in `calculateShareSale` that repeatedly divides the share price by a large value (possibly also incorrectly calculated) for every 1e6 shares sold.

I believe the current constant `SHARESPERPRICEUPDATE` should actually be a relative amount (relative to the total number of shares) rather than a fixed amount, and the calculation for computing the new share price should be based tested to scale more smoothly.

There are a few other oddities about this routine that should maybe be addressed while fixing it:
- `this.shareSalesUntilPriceUpdate` appears to have been added to keep track of the "remainder" of shares sold in between increments of `SHARESPERPRICEUPDATE` - but the value is never updated, so one could in theory cheese the system by repeatedly selling `SHARESPERPRICEUPDATE - 1` shares and never affect the stock price.
- We may also wish to add the Corp Softcap modifier as a factor here so that the overall sale value is nerfed idendically to dividends.

**Comment by Leappin** [comment]
Dug into this a bit more since it didn't sit right that it was only happening to me and nobody else. 

This occurs when you have negative profits for your company as a whole. The compounding mechanic in `calculateShareSale` takes stock price into account, and updates stock price to the target stock price, `this.determineValuation() / (2 * (this.totalShares + sharesSold - this.numShares))`, as if you had sold `SHARESPERPRICEUPDATE` (1e6) shares. However since the stockValue is now 0, further iterations will just multiply shares sold by zero. 

The diminishing returns appear due to a surplus of funds that is big enough to survive negative profits being multiplied by 315e3. If you don't have sufficient funds stored, then going above 1e6 will just not change the money received. 

Returns at 300b with profit of $-362,260.
![bitburner_2022-04-01_16-27-17](https://user-images.githubusercontent.com/102821798/161336756-43f8df98-c774-45dc-9200-8827ebc2657c.gif)

Returns at 3b with profit of $-358,755
![bitburner_2022-04-01_16-29-25](https://user-images.githubusercontent.com/102821798/161336920-856fc31f-01f6-4626-b254-e8d4bfe808da.gif)

I suppose a potential balance "fix" would be to min negative profits to 0 when calculating stock price so valuation doesn't go below your stored income. This is definitely a bit of an edge case though, so could be ignored if we accept selling stocks while you have negative incomes will immediately tank your stock price towards zero, making it trivially easy to buy all outstanding shares back.

**Comment by TheRealMaxion** [comment]
Share price drops a lot after selling a lot of shares with high share price and low positive profits and funds too, but I'm not so sure that being able to buy them back easily is that big of an issue since there is a cooldown on selling shares.
