### ISSUE TITLE
Bug: Overview collapse button does not respond to touch input

### ISSUE THREAD

**Issue by DavidGrinberg** [danielyxie/bitburner#3341]
**Steps to reproduce:**
1. Open bitburner on a machine with touchscreen
2. Use finger to touch the collapse/expand button on the top right of the overview menu

**Expected result:** The menu would expand/collapse accordingly

**Actual Result:** Nothing happens

Version: 1.6.3 6c8a46d3

**Comment by phyzical** [comment]
@DavidGrinberg i dont think anyone has done much testing with touch screens, should just be matter of making sure all .clicks support .touch 

was there any other spots you have noticed that are not compatible?

**Comment by DavidGrinberg** [comment]
No, this was the only spot I was able to find that failed on touch. All the other buttons (e.g. other collapses, left sidebar buttons, focus/unfocus, travel, etc) seemed to work fine.

**Comment by Hedrauta** [comment]
🤔 isn't a touchscreen-touch just a click on the position you touched??

**Comment by alainbryden** [comment]
It's possible that a few clickable elements are implemented using a onmouseup or onmousedown event which isn't automatically translated by the touch device.

**Comment by Snarling** [comment]
The issue is the react-draggable is disabling the click functionality of the touch inputs inside the draggable area, more details [here](https://github.com/react-grid-layout/react-draggable/issues/550#issuecomment-947166613).

The same thing affects the tail titlebar buttons. I'm going to propose a fix that just adds onTouchEnd events to perform each of the normal click functions.
