### ISSUE TITLE
Someone explain browserlist to me

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#3407]
I ran `browserlist update-db` because the compiler was yelling at me. 

Then building the game started having weird errors like

```
Unexpected token (121:29)
...
scrollId = doScroll() ?? 0;
```
Obviously meaning it doesn't understand the null coalescent operator.

I had to change  this file:

https://github.com/danielyxie/bitburner/blob/dev/.browserslistrc

from `last 4 versions` to `last 8 versions` and I don't know why

someone explain this to me.

**Comment by ChrissiQ** [comment]
I don't know why changing browserslist settings fixes this issue, but I was curious so I played around, and I have just a little insight:

Something is going wrong with the transpilation step after the browserslist db update - I don't really know why - it could be related to the `react-refresh` module since that is wrapping the babel loader.  I've done a few similar webpack setups, and sometimes certain components can't be updated without updating webpack and many of the related webpack modules.  It can just be version-update dependency hell sometimes, but I like diving into this stuff sometimes, and this one actually wasn't too bad.  I've done much worse webpack migrations 😄 

So based on that, I tried updating webpack, and what do you know - after migrating, the error goes away and I'm able to build with the old browserslist setting (`last 4 versions` instead of 8).

There is still a warning that I didn't try to fix, so this isn't a full solution and it needs more checks against regressions/issues. I played around a little and everything looks normal at first glance, but I'm not that confident since I only just poked around and could have missed something.  But here's my diff to migrate webpack 4->5 with a successful compile and your old browserslist setting:

```diff
diff --git a/.browserslistrc b/.browserslistrc
index 1af9a66c..aa635980 100644
--- a/.browserslistrc
+++ b/.browserslistrc
@@ -1,3 +1,3 @@
-last 8 versions
+last 4 versions
 not dead
 not ie <= 11
diff --git a/package.json b/package.json
index a11d09d8..ea6297b5 100644
--- a/package.json
+++ b/package.json
@@ -54,7 +54,7 @@
     "@babel/preset-typescript": "^7.15.0",
     "@microsoft/api-documenter": "^7.13.65",
     "@microsoft/api-extractor": "^7.18.17",
-    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.1",
+    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
     "@testing-library/cypress": "^8.0.1",
     "@types/acorn": "^4.0.6",
     "@types/escodegen": "^0.0.7",
@@ -75,23 +75,23 @@
     "eslint": "^7.24.0",
     "file-loader": "^6.2.0",
     "fork-ts-checker-webpack-plugin": "^6.3.3",
-    "html-webpack-plugin": "^3.2.0",
+    "html-webpack-plugin": "^5.5.0",
     "http-server": "^13.0.1",
     "jest": "^27.1.0",
     "jsdom": "^15.0.0",
     "lodash": "^4.17.21",
-    "mini-css-extract-plugin": "^0.4.1",
+    "mini-css-extract-plugin": "^2.6.0",
     "prettier": "^2.3.2",
     "raw-loader": "^4.0.2",
-    "react-refresh": "^0.10.0",
+    "react-refresh": "^0.12.0",
     "regenerator-runtime": "^0.13.9",
     "source-map": "^0.7.3",
     "start-server-and-test": "^1.14.0",
     "typescript": "^4.2.4",
-    "webpack": "^4.46.0",
-    "webpack-cli": "^3.3.12",
-    "webpack-dev-middleware": "^3.7.3",
-    "webpack-dev-server": "^3.11.2"
+    "webpack": "^5.72.0",
+    "webpack-cli": "^4.9.2",
+    "webpack-dev-middleware": "^5.3.1",
+    "webpack-dev-server": "^4.8.1"
   },
   "engines": {
     "node": ">=8 || <=9"
@@ -110,9 +110,9 @@
     "format": "prettier --write .",
     "format:report": "prettier -c .",
     "start": "http-server -p 8000",
-    "start:dev": "webpack-dev-server --progress --env.devServer --mode development",
-    "start:dev-fast": "webpack-dev-server --progress --env.devServer --mode development --fast true",
-    "start:container": "webpack-dev-server --progress --env.devServer --mode development --env.runInContainer",
+    "start:dev": "webpack-dev-server --progress --env devServer --mode development",
+    "start:dev-fast": "webpack-dev-server --progress --env devServer --mode development --fast true",
+    "start:container": "webpack-dev-server --progress --env devServer --mode development --env runInContainer",
     "build": "webpack --mode production",
     "build:dev": "webpack --mode development",
     "lint": "eslint --fix --ext js,jsx,ts,tsx --max-warnings 0 .",
diff --git a/webpack.config.js b/webpack.config.js
index e2212c53..a318c3bc 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -28,8 +28,10 @@ module.exports = (env, argv) => {
   const devServerSettings = {
     hot: true,
     port: 8000,
+    devMiddleware: {
       publicPath: `/`,
       stats: statsConfig,
+    },
   };
 
   // By default, the webpack-dev-server is not exposed outside of localhost.
@@ -176,13 +178,12 @@ module.exports = (env, argv) => {
       removeEmptyChunks: true,
       mergeDuplicateChunks: true,
       flagIncludedChunks: true,
-      occurrenceOrder: true,
       sideEffects: true,
       providedExports: true,
       usedExports: true,
       concatenateModules: false,
-      namedModules: false,
-      namedChunks: false,
+      moduleIds: 'size',
+      chunkIds: 'total-size',
       minimize: !isDevelopment,
       portableRecords: true,
       splitChunks: {
@@ -198,6 +199,7 @@ module.exports = (env, argv) => {
     devServer: devServerSettings,
     resolve: {
       extensions: [".tsx", ".ts", ".js", ".jsx"],
+      fallback: { "crypto": false },
     },
     stats: statsConfig,
   };

```

**Comment by HeinousTugboat** [comment]
Dug into this a little bit. It's definitely because it's dropping the rewriting for `??`. Specifically it's because Samsung 12 support is dropping. `latest 5 versions` is the lowest number that builds, and checking the diff between those two shows Samsung 12 changing which doesn't support `??`. I verified `latest 3 versions` works if you include`safari >= 13`.

Related issues elsewhere on the Internet: 

https://github.com/facebook/create-react-app/issues/9468
https://github.com/facebook/create-react-app/pull/8526
