### ISSUE TITLE
ns.nFormat() magnitude error when used on RAM

### ISSUE THREAD

**Issue by ph-hoffmann** [danielyxie/bitburner#3478]
## Description
The "value" generated by `ns.nFormat(ram, "0.00b")` is off by some order of magnitude (10^9 to be specific) when used in combination with `ns.getServerMaxRam()` or `ns.getServerUsedRam()`.

## Steps to reproduce
1. use `free` in terminal
2. use following script
3. compare output

## Script
```
/** @param {NS} ns */
export async function main(ns) {
    let ram = ns.getServerMaxRam("n00dles");
    ns.tprintf("RAM: %s", ns.nFormat(ram, "0.00b"));
}
```

## Terminal Output
```
[n00dles ~/]> free
Total:     4.00GB
```

## Script Output
```
[home ~/]> run test.js 
RAM: 4.00B
```

Version: Bitburner v1.6.4 (fbb99c17)
Script API: ns2

**Comment by phyzical** [comment]
good spot `const gigaMultiplier = { standard: 1e9, iec60027_2: 2 ** 30 };` looks like its set to 1e9 instead of 10e9

**Comment by Snarling** [comment]
@phyzical The G isn't being lost, it's never being added. nFormat doesn't use the gigaMultiplier constant, that is only used for formatRam which is basically the game's hardcoded formatting for displaying ram values. formatRam isn't exposed for player access. `ns.nFormat(4,"0.00b")` just formats the number 4 as a byte value using numeraljs so this is expected output.

@ph-hoffmann see above, nFormat is just a direct wrapper for numeraljs formatting, IF you want to format a value that represents GB as a byte value, you need to account for that 1e9 factor yourself. nFormat shouldn't be changed, but maybe a new function can be added to give the player access to formatRam.

**Comment by ph-hoffmann** [comment]
I guess the problem stems from the fact that the numbers are actually not correct internally.

The base function (in Numeral.js) excepts numbers to be in base magnitude (Bytes in this case). It seems 
the game internally stores 1 GB (1e9 Bytes) as 1 though.

I've applied the workaround mentioned by @Snarling for now.

In my opinion, I'd rather fix how the amount of RAM is stored then create a new function. That only makes things confusing. This is, if storing RAM amounts in the current way was not a delicate decision of course.

**Comment by Snarling** [comment]
So would you want ingame functions like getServerMaxRam to return values like 128000000000? I would much rather that return 128 and let me know that it's in units of GB. I think the documentation makes it pretty clear that the values from these sorts of functions are in GB, and I don't think I've heard of anyone messing up their program because they wrote it expecting the game to give them byte values instead of GB.

IMO bytes are not a useful unit to work with when you're almost always dealing with billions of them. But they are what's expected by numeral for doing standard unit formatting, so that just means converting before formatting is necessary. My opinion is we can close this issue with no action needed.

**Comment by Martin-Pitt** [comment]
As a newcomer to the game (started about a month ago), I enjoyed the fact that RAM cost values were in simple GB rather than having to deal with bytes.

It is a little unusual to have the base values in GB than B, but it was not really surprising and instead very convenient.

The game had been clear and consistent throughout the interfaces and within the documentation.
