### ISSUE TITLE
Log box Position 

### ISSUE THREAD

**Issue by apdjz** [danielyxie/bitburner#3535]
I was wondering if it was possible to set the position of the log box when it is opened. For example top right. I was wanting to evenly space them in a column next to the overview.

**Comment by Snarling** [comment]
This type of question is better asked on the discord instead of as a github issue.

Here's a link to a previous answer I provided to a similar question on discord: https://discord.com/channels/415207508303544321/931147989307764786/935793825752940555

You can set the position of the most recently opened log box with

```
let desiredX="100px",
  desiredY="100px";
Object.assign(document.querySelector(".react-draggable:last-of-type").style,{left:desiredX,top:desiredY});
```

**Comment by apdjz** [comment]
I agree but the link was broken for me.
