### ISSUE TITLE
Corporation product development - bug or intentional behaviour?

### ISSUE THREAD

**Issue by Vic1970** [danielyxie/bitburner#3563]
Bitburner v1.6.4 (00628a8c)

When developing new products in a division of your corporation, they are developed sequentially whether you develop them in the same city or not.

If I have 200 engineers / operators in Chonqing and I tell them to develop a new product, why do they have to wait to start until a separate team of 200 engineers / operators in the same division but in Aevum has finished their development of a separate product?

Why can't they be developed simultaneously?

This may be deliberate behaviour for a balance issue or something else I haven't considered, but if not then simultaneous product development by different cities in the same division should be possible.  

Thanks for a great game.

**Comment by phyzical** [comment]
its due to balancing probably, but also due to products being shared across divisions.

though looking at the source we do only use the  office it was created in to actually develop the product, so i dont see any reason why we couldnt allow multiple products to be produced at once, and should just be a matter of wrapping https://github.com/danielyxie/bitburner/blob/dev/src/Corporation/Industry.ts#L1025 this break in a bool that is only true if another product for the same city has already been progressed in this tick

**Comment by PSEUDOSTAGE** [comment]
This would definitely be a fairly significant shift in balance. I get that having to hire the employees in each city mitigates some of the benefit of being able to knock three products out at once but I can immediately think of scenarios where that simply wouldn't matter to me. I could get three products up at the beginning cycle in the time of one, I'd almost immediately be able to grab an investment and start fleshing out the corp, so I'd probably do that every single time even if my plan were to only invest in one city following that.

Not against the idea mind you, but it needs to be stated that this would make corps quite a lot faster to grow.

**Comment by Vic1970** [comment]
Apart from hiring the employees you also need to be able to afford the office expansion - this might mitigate some of the immediate start-up rush you are referring to.  Cost of office expansion is negligible relative to corp funds by later stages of corp play, but pretty significant at the start IIRC.  I've only done one corp so far, so I defer to your better understanding.
