### ISSUE TITLE
Feature Request: Track money earned by source in stats screen

### ISSUE THREAD

**Issue by dleblond312** [danielyxie/bitburner#3595]
Given the scale of variability in earning money between sources. It would benefit users to understand in any given augment loop what is the primary source of income (and extending this data to the player object as a new moneySinceAugment object. There are a variety of sources, some of which the player can infer via API and some there is no access to today. Requiring access to Formulas could be a logical contraint on this data access.

**Hacking:** This is partially inferred from the Active scripts page, but since it merges multiple sources it lacks accuracy, the player could write all hack results to a port and aggregate, but the port limits might cause significant rollover for this.

**Stock:** This one is trivial to track as the API for selling handles it well and it's synchronous.

**Gang:** I don't believe there is an in-game UI or an API for calculating this, you can see tick rate in the gang tab, but not an aggregate over time.

**Bitburner:** I don't believe there is an in-game UI or an API for calculating this.
**Corporation:** I don't believe there is an in-game UI or an API for calculating this.
**Hacknet**: I don't believe there is an in-game UI or an API for calculating this.
There are others I might not have encountered yet

**Comment by phyzical** [comment]
So atm this data is exposed on the character overview 

https://github.com/danielyxie/bitburner/blob/dev/src/ui/CharacterStats.tsx#L174
and structure looks like
https://github.com/danielyxie/bitburner/blob/dev/src/utils/MoneySourceTracker.ts#L11

but it is not exposed in any way from what i can see via the api, so we could consider adding a singularity function to expose this (maybe getIncomeSinceLastAugment and getBitnodeIncome ) OR look at exposing the moneysource A (income since last augment) and B (income for current bitnode) on the player object that is returned via getPlayer

@hydroflame what do you think?

**Comment by Undeemiss** [comment]
I'm fairly sure hydro has stated in the past he doesn't want to expose that, so that it isn't a breaking change if the way that info is displayed/calculated changes at any point.
