### ISSUE TITLE
(Beta) Multi-line string notation works in syntax highlighting but not in execution

### ISSUE THREAD

**Issue by typicalTYLER** [danielyxie/bitburner#374]
I have a multi-line string in a script, and the syntax highlighting and dynamic checking in nano indicates it should be functional, but running the script causes an error

```
getBitNodeMultipliers();

BLOCK_START_TAG = "//// START AUTO UPDATED CODE BLOCK ////";
BLOCK_DEFAULT_CONTENTS = `//Skill Multiplier Constants, update after augmentations
hackmult = 1.0000;
growmult = 1.0000;
//Bitnode Multiplier Constants, update after changing Bitnodes
bitnodehackmult = 1.0000;
bitnodegrowmult = 1.0000;
bitnodeweakenmult = 1.0000;`;
BLOCK_END_TAG = "//// END AUTO UPDATED CODE BLOCK ////";
```

![image](https://user-images.githubusercontent.com/6762150/43095350-2700ca24-8e7b-11e8-8e2f-bbf21e09e9da.png)

![image](https://user-images.githubusercontent.com/6762150/43095291-0578ee5e-8e7b-11e8-9402-16258ad18920.png)

**Comment by danielyxie** [comment]
It looks like multiline strings were [introduced in ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Specifications), which means they are not supported by the Netscript 1.0 Interpreter since it is only ES5.

The syntax highlighting/syntax checking works because that uses a ES6+ parsing mode.

Since it seems like you know what you're doing, you should consider using [NetscriptJS](http://bitburner.readthedocs.io/en/latest/netscriptjs.html)
