### ISSUE TITLE
System Time changes cause all offline progress to generate negative income.

### ISSUE THREAD

**Issue by Zanda250** [danielyxie/bitburner#3827]
I recently had to change my system time backwards due to a windows 11 bug periodically pulling an incorrect time from Microsoft's time.windows.com server (roughly 8h ahead of real time). Now all offline income is negative instead of positive, and offline progress for faction work or other activities is not tracked. I assume the issue is in the offline income calculation receiving a negative time in the parameter. 

To reproduce:
Change the time forward while offline (8h for my case).
Start the game at the new time.
Save and close the game. 
Change the time back to current.
Open the game. (May need to manually pick save to import, as game may give the option of two save states, choose the most playtime with the earlier save date to get the newest save).
Offline income will now be negative for all future offline progress.

Game Version: v1.7.0 (00adc2ff)

[bitburnerSave_1654626240_BN4x1.zip](https://github.com/danielyxie/bitburner/files/8855705/bitburnerSave_1654626240_BN4x1.zip)

**Comment by phyzical** [comment]
i think this is solely due to https://github.com/danielyxie/bitburner/blob/dev/src/Script/ScriptHelpers.ts#L17

i will add some logic to just make this 0 if its ever negative to avoid the problem going forward

**Comment by phyzical** [comment]
hmm actually thinking about this further, by doing the above it will just make it super exploitable. 

based on the logic this will only occur once and then once "player.lastUpdate" is refreshed everything will be normal again. 

i think this is closable in the sense it sucks but its trying to stop people from cheating themselves :)

**Comment by AngrySquirrell** [comment]
Hey, i've got the same annoying bug, although it goes a bit further for me (idk for you): 
The negative income keep decreasing, even after letting my scripts running.
It got from +100k/s to a measly -120$/s this morning and -138$/s this evening. 
Eventhought it's seems to be minor, it nullify any offline time and end up making me lose a considerable amount of money has it uses this value to calculate afk gain.
I understand the anti-cheat argument, but for me who suffered once of this Windows11 bug, it made it really annoying to progress. So maybe you shound't 0 any negative amount of money made, I think you should fix the negative income.
Anyway, thank you for reading this :)

ps: Here's a picture of the mentioned negative income 
[ Total production since last Augment Installation: $751.148m ($-140.565 / sec) ]
![image](https://user-images.githubusercontent.com/91453633/180615567-ae89179b-b0fe-4177-906f-4607dbb4f1de.png)
