### ISSUE TITLE
Kill *script name* not working

### ISSUE THREAD

**Issue by TheOnlyHope** [danielyxie/bitburner#3833]
Wen I was on my home server, I could never kill a script with kill *script name*. It would just say that no such script existed and therefore no script was killed. The script would, however, be killed if I used killall.  The scripts I was using was located on my home server aswell.

The version of the game I was using was v1.7.0 (00adc2ff)

**Comment by stalefishies** [comment]
`kill` is for killing a specific instance of a script, so you have to follow the script name with the arguments used in the instance of the script you want to kill. You can check `help kill` for more info about this.

`killall` kills all scripts with a given script name, so that's why that was working when `kill` did not.

**Comment by TheOnlyHope** [comment]
Thanks :)
