### ISSUE TITLE
Runtime Error: n.substring is not a function when using ns.sprintf

### ISSUE THREAD

**Issue by yoezerh** [danielyxie/bitburner#3840]
## Game version

Bitburner v1.7.0 (b60f3da8)

## Details

I'm encountering the following error when using ns.sprintf on my scripts.

```
RUNTIME ERROR
test.js@home (PID - 6)

n.substring is not a function
stack:
c@https://danielyxie.github.io/bitburner/dist/vendor.bundle.js:30:257145
o@https://danielyxie.github.io/bitburner/dist/vendor.bundle.js:30:254315
value@https://danielyxie.github.io/bitburner/dist/main.bundle.js:19:1226954
a/<@https://danielyxie.github.io/bitburner/dist/main.bundle.js:1:294122
main@home/test.js:3:18
executeJSScript@https://danielyxie.github.io/bitburner/dist/main.bundle.js:19:101335
```

## Script to reproduce the issue

```
export async function main(ns) {
	const test = ns.sprintf('simple log');
}
```

## Steps to reproduce the issue

1. Create a simple script given above, save it as 'test.js'
2. Run the script using 'run test.js'

# include (where relevant)

- [ ] Save file
- [x] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by dbachran** [comment]
I am also affected by this. But only as of recently, I think.

I am usually playing Bitburner via Steam, where `ns.sprintf()` works without any issues.

When importing my savegame in the web browser (Chrome) I get the same error as the original reporter.

I only noticed that issue recently (as of v1.7.0). But, I did not play in Chrome regularly, just as an exception, from time to time. So it may have been there longer already or may be caused by a Chrome update as well...

ciao, daniel :-)
