### ISSUE TITLE
NotFoundError: Node.removeChild: The node to be removed is not a child of this node (at "BitVerse")

### ISSUE THREAD

**Issue by Cle-O** [danielyxie/bitburner#3844]
### How did this happen?
Executed backdoor on world_daemon in BN11.3 --> instant error.

Reloaded the game with the last save, did the same again and it worked.

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Node.removeChild: The node to be removed is not a child of this node
* Page: BitVerse
* Version: v1.7.0 (b60f3da8)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
* Features: lang=de cookiesEnabled=true doNotTrack=unspecified indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
``
[RECOVERY_BITBURNER_1655189039.zip](https://github.com/danielyxie/bitburner/files/8897137/RECOVERY_BITBURNER_1655189039.zip)
`

**Comment by Snarling** [comment]
Most likely this is caused by you modifying the DOM tree manually, probably due to your removePopups.js,

When you manually move or remove content from the page that is being managed by React, React will run into an error when it tries to remove that content later on. This is why reloading and trying again worked with no issues - since you had not manually removed any elements the second time around.
