### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of string 'm' (at "ScriptEditor")

### ISSUE THREAD

**Issue by tanis0** [danielyxie/bitburner#3845]
### How did this happen?

I have not played since 8/2021 and was unable to use the ls command at all. I got the recovery screen soon afterward and hit the soft reset button and everything seemed fine. I completed the bitnode I was on and started BN-13, then let some scripts run while I went to bed. Today, everything seemed fine until I tried to create a new .js file and got a recovery screen. I tried refreshing, but no joy.

STEPS TO REPRODUCE:
1. Load the save in Chrome (I have not tested other browsers)
2. Use nano to create a new .js file
3. Reach recovery screen

Please fill this information with details if relevant.

- [X] Save file
- [ ] Minimal scripts to reproduce the issue
- [X] Steps to reproduce

### Environment

* Error: TypeError: Cannot assign to read only property '0' of string 'm'
* Page: ScriptEditor
* Version: v1.7.0 (b60f3da8)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
``
[RECOVERY_BITBURNER_1655281415.txt](https://github.com/danielyxie/bitburner/files/8907329/RECOVERY_BITBURNER_1655281415.txt)
`

**Comment by Snarling** [comment]
Looks like the issue is due to this in your save file: 
![image](https://user-images.githubusercontent.com/84951833/173902029-3bbb0e4c-12a2-4d9a-beaa-b33fdd8536b2.png)

Here's that same portion in my working save file: 
![image](https://user-images.githubusercontent.com/84951833/173902348-a4f43eed-d2c8-48b4-bd68-84670d859c7d.png)

Deleting the extra data from your EditorTheme entry seems to fix the issue:
[FixedRecovery.txt](https://github.com/danielyxie/bitburner/files/8912267/FixedRecovery.txt)

Not sure how the offending data got into your save though.

**Comment by tanis0** [comment]
So far, so good. Thanks! The original save was from 8/10/2021.

I don't know why the editor worked for the original bitnode before breaking, so I'll update this issue if the problem recurs, though I can edit the save myself since you've pointed out the invalid data.
