### ISSUE TITLE
Applying for or quitting a job cancels any in-progress task

### ISSUE THREAD

**Issue by nolanfu** [danielyxie/bitburner#3856]
Applying for a new job, or quitting an existing job, will cancel any in-progress grafting (the real problem) as well as studying, gym workouts, faction work, or creating a program. Bladeburner tasks are not affected by this and will maintain progress during a job application / quit.

Also, if you quit a job while doing a task that affects your stats, you'll also get a message about how you wrapped up your job shift, with an elapsed time that matches up with when you started whatever you were actually doing, and work "earnings" based on what you were actually doing.

Version: Bitburner v1.7.0 (b60f3da8)

Steps to reproduce: 

- Start a non-job related task, like studying at university.
- Apply for a job at foodnstuff. Your study session will get canceled.
Or:
- Have a job at foodnstuff.
- Start a non-job related task, like studying at university.
- Quit your job at foodnstuff.  Your study session will get canceled, and the data for the study session will get put into the template for quitting a job shift early.

**Comment by Snarling** [comment]
Yes this is due to a bug when you quit a job while performing any task. If you're currently working when you quit, you'll break your save. If you're doing something other than working for a company, it'll act like you just finished your work shift.

There's a fix ready to go addressing this, it just hasn't been applied yet. For now I would recommend just not quitting a job while you're in the middle of anything, if you need to quit a job, just wait until you're no longer busy.
