### ISSUE TITLE
recursive writing to textfile doesn't work.

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3895]
When writing to a textfile from a recursive function, it doesn't work without a ns.print inside the function (for example).
The initial clearing happens, all writings inside the "buildServerTree" function aren't happening.
When enabling "ns.print(\`childServer: ${child.childServer}\`)" everything works fine.
I could provide a save file too when needed.

Reproduce:
- in main script call:
```
const serverTreeFile = 'serverTree.txt'
void await addToLog(ns, serverTreeFile, '', 'w')
void await buildServerTree(serverTree, { childServer: 'home' }, serverTreeFile, 0, ns)
```

it uses the following helper functions
```
const processedTreeServers = new Set()
/**
 * 
 * @param { [{ childServer: string; server: string; serverRam: number; serverHasRootAccess: boolean; serverMaxMoney: number }] } serverArr 
 * @param { { childServer: string; server: string; serverRam: number; serverHasRootAccess: boolean; serverMaxMoney: number } } server 
 * @param { string } logFile 
 * @param { number } level 
 * @param { NS} ns 
 */
const buildServerTree = async (serverArr, server, logFile, level, ns) => {
	const { childServer, serverRam, serverHasRootAccess, serverMaxMoney } = server
	
	if (processedTreeServers.has(childServer)) return

	void await addToLog(ns, logFile, `${treePadding(level)} ${childServer} [ hacked: ${serverHasRootAccess ? 'Y' : 'N'} / ${serverRam ?? 'n/a'} Gb / ${Amount.format(ns, serverMaxMoney || 0 )} ]`, 'a')
	
	processedTreeServers.add(childServer)

	const childServers = serverArr.filter((x) => x.server === childServer)
	for (let child of childServers) {
// ==> [Without this enabled is mostly writes nothing]  // ns.print(`childServer: ${child.childServer}`)
		void await buildServerTree(serverArr, child, logFile, level + 1, ns)
	}
}

/**
 * 
 * @param { number } level 
 * @returns { string }
 */
const treePadding = (level) => {
	const space = '   '
	const padding = Array(level).fill(space).join('')
	return `${padding}>`
}

/**
 * 
 * @param {NS} ns 
 * @param {string} logfile 
 * @param {string} message 
 * @param {string} mode 'w' | 'a'
 */
export const addToLog = (ns, logfile, message, mode) => {
	return ns.write(`${logPath}/${logfile}`, `${message}\n`, mode)
}
```

**Comment by edbrannin** [comment]
I'm not @danielyxie, but:

1. Can you post a complete script that shows the issue?  I mean something that has main(), does not import your own code, and shows what your problem is.
2. What's the actual error message that you're seeing?  Or if it's not an error message, what's the specific result that you're seeing that's showing a problem?
3. I'm not able to get your code to run without changes -- it seems like you've left out how `serverTree` is defined, and `Amount` isn't defined.  (Don't answer this directly, just update with a complete script.
4. I realize you're trying to nail down a bug, and I support that, but maybe consider returning an array of strings up the recursive call stack and writing them all at once?

**Comment by Granaat** [comment]
While I was creating the stripped version, I noticed I didn't reset a Set, hence it skipped the servers.
