### ISSUE TITLE
TypeError: t.text.matchAll is not a function or its return value is not iterable (at "Terminal")

### ISSUE THREAD

**Issue by bfallstrom** [danielyxie/bitburner#3911]
Version 1.7.0 (0b22e87e)
Recovery mode activated when trying to run eval at command line
command line input: `eval 450560000*2`
error message: `TypeError: t.text.matchAll is not a function or its return value is not iterable (at "Terminal")`

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by Snarling** [comment]
When you say "command line" what are you referring to, the terminal input prompt? If I type the above I get `Command eval not found`. In the developer console I get "Uncaught SyntaxError: Unexpected number"

If you have an alias named eval, we need to know what that alias is and what the related script is doing, otherwise we cannot reproduce your issue.

**Comment by bfallstrom** [comment]
My apologies; I meant expr not eval. I misremembered, and since it crashed, I didn't have the line I entered available to copy and paste. This was in fact in the terminal input prompt.

**Comment by bfallstrom** [comment]
also I just reproduced with `expr '2*2'` so it wasn't a matter of the argument needing to be quoted.

**Comment by Snarling** [comment]
Thanks. Yeah it looks like expr is just completely broken right now due to an update earlier.

The original ANSI update code made sure that item.text was a string, and alluded to this error in a comment: https://github.com/danielyxie/bitburner/blob/36c7ef1ad7ea8bb69fca23bce5883a3c2e23f1e0/src/Terminal/ui/TerminalRoot.tsx#L272

But that some safeguard didn't get copied over when it was refactored as a separate component earlier:

https://github.com/danielyxie/bitburner/blob/6b18bfb14560da733b06973e717b968c06f290dd/src/ui/React/ANSIITypography.tsx#L73

#3908 is the same issue.
