### ISSUE TITLE
Crash when trying to open documentation

### ISSUE THREAD

**Issue by p-stevenson** [danielyxie/bitburner#3945]
Game returns the following error when attempting to open any file listed in the tutorial/documentation section.

![bitburner_error](https://user-images.githubusercontent.com/54287958/182039242-aa2c093b-0398-4396-9a8d-98db81718e2d.png)

**Comment by phyzical** [comment]
what version? steam/browser? which browser/OS?

**Comment by twofivetwo** [comment]
sorry that was incredibly lazy of me. thank you.

v.1.7.0
steam
windows 11

**Comment by hydroflame** [comment]
For anything trying this out. This happens because electron attempts to open external link using windows default "explorer.exe" program. (which is not internet explorer, it's just "try to open whatever this is, the program")

For some reason, some users don't have a default explorer.exe set and it causes this.
