### ISSUE TITLE
Toasts don't show when infiltration focus window is active

### ISSUE THREAD

**Issue by scm04** [danielyxie/bitburner#3947]
Toasts seem to be hidden behind the infiltration focus window. #1643 fixed this same issue for the focus windows for working and committing crimes.

Game version: Bitburner v1.7.0 (cfcdc254)

### Steps to Reproduce
- Navigate to the infiltration page for any company.
- Start the infiltration, then click the "Save" button in the stats overview.

### Expected behavior
The "Game Saved!" toast should appear.

### Actual behavior
No toast ever appears.

**Comment by phyzical** [comment]
not 100% but i think we just need to use a createDialog box around this? https://github.com/phyzical/bitburner/blob/dev/src/Infiltration/ui/Game.tsx#L119

**Comment by Snarling** [comment]
No popups are shown during the infiltration screen, because in GameRoot.tsx the infiltration page has withPopups = false.

https://github.com/danielyxie/bitburner/blob/69eda4340e4fc63716fd1f8c7b039a32a7fcbf2f/src/ui/GameRoot.tsx#L332-L337


And withPopups is used to determine whether to show all forms of popup, including toasts (the Snackbar).

https://github.com/danielyxie/bitburner/blob/69eda4340e4fc63716fd1f8c7b039a32a7fcbf2f/src/ui/GameRoot.tsx#L529-L537

I'm not sure this is a bug, it seems intentional. I think at some resolutions, toasts could obscure parts of the game.
