### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Terminal")

### ISSUE THREAD

**Issue by Lee2ee** [danielyxie/bitburner#3971]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
          I was doing a tutorial
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v1.7.0 (cfcdc254)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
* Features: lang=ko-KR cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```
[RECOVERY_BITBURNER_1660126369.zip](https://github.com/danielyxie/bitburner/files/9299092/RECOVERY_BITBURNER_1660126369.zip)

I just want to play the game

**Comment by Snarling** [comment]
@Lee2ee @hwaamsanseok @task58 @HelpboyLP
Related issues #3961 #3956 #3955 #3952 
I noticed that all of these related issues were filed by users who use a browser language other than English.

I found that React has [an issue](https://github.com/facebook/react/issues/11538) where it can cause these types of errors due to Google translate or maybe other similar translation extensions modifying the DOM:

There is a workaround [here](https://github.com/facebook/react/issues/11538#issuecomment-417504600) which we may be able to implement as a solution to address these errors.

**Comment by phyzical** [comment]
hmm given there is a "slowdown" by implementing we might want to consider hiding it behind a setting toggle like "using google translate plugin" or something? though reading the desc of the workaround this might not be possible as it implies its a prerender workaround for the whole app?

**Comment by Snarling** [comment]
I had already posted more on #bug-reports but I found a better workaround also in that react issue thread. The issue happens:
A] when a text node is being removed directly from its parent element, and 
B] when something is being added directly before a text element within the same parent element

The issue happens because google translate moves the text node to a different parent element (it creates a font tag, and moves the text into the font tag). So when the text node is being removed directly from what its parent "should" be, it's not there and the error is thrown.

In either case this can fixed by ensuring that text nodes are wrapped by e.g. a span tag, and conditions are applied to the span element instead of the text node. Then when React is trying to remove just the text due to some condition, it'll remove the entire span tag (which it can still find because it isn't moved by google translate)
