### ISSUE TITLE
Naming standardization issues with stock data

### ISSUE THREAD

**Issue by finn-e** [danielyxie/bitburner#4005]
The capitalization and word choice between the now moved (which in my opinion I think they made more sense in getPlayer() than as their own functions) ns.stock.has4SDataTIXAPI() and the ns.stock.purchase4SMarketDataTixApi() is inconsistent. The same is true for has/purchase of the Data/MarketData, WSE/Wse and TIXAPI/TixApi.
Could these please be standardized? I understand that this would be a breaking change, so maybe we can just deprecate the current choices of one or the other.

**Comment by phyzical** [comment]
while i agree, the problem is changing even 1 function upsets many casual players. imagine coming back about a month and having to sift through a pile of scripts you've completely forgotten what they do to adjust the names of functions.

on top of that imagine your not a savvy programmer you would probably give up.

Granted if we handle the deprecation appropriately it would probably be fine. 👍
