### ISSUE TITLE
Game does not save

### ISSUE THREAD

**Issue by paulsmith1232** [danielyxie/bitburner#4078]
The game does not save any progress, either automatically or by using the manual save feature. I've exported my 'save' and tried to import it, only to get the following error:

FAILED TO GET IBD (Object Event)

I'm playing on v2.0.2

**Comment by quacksouls** [comment]
> FAILED TO GET IBD (Object Event)
> 
> I'm playing on v2.0.2

Are you using a web browser to play the game?  I get the above error message all the time whenever I want to import a save file into Firefox.  The reason is that I have customized Firefox by installing various addons, including ad-block and privacy addons, and other customized privacy settings.  If I want to use a web browser to play the game, I would use another browser.  For example, try installing another browser.  Using the default settings of this new browser, load the game and import your save file.  I have tested this with the COB gang, i.e. Chrome, Opera, Brave.

**Comment by paulsmith1232** [comment]
It was my Chrome extensions that were the issue. Thanks for the help.
