### ISSUE TITLE
Generate Ip Adresses Fails to Solve Properly

### ISSUE THREAD

**Issue by theweirdEd** [danielyxie/bitburner#4163]
[BitburnerContractBugSave.txt](https://github.com/danielyxie/bitburner/files/9648245/BitburnerContractBugSave.txt)

The text file is an exported JSON save file. Just go into the game and run the Script found at /UtilScripts/CCTGetter.js It will display all Details of the Coding Contracts and attempt to solve them. It will fail at the IP Generator Contract as seen in the Picture. I tried my own solver and then some I found on the web to see if I got the solution wrong, but theirs did not get accepted as well. The Script Previously already resolved multiple instances of the IP Generator Contract
![BugReportBitburner](https://user-images.githubusercontent.com/42383795/192338843-9fafe63d-cb27-41f5-bf5d-c7cd6073df44.PNG)

**Comment by quacksouls** [comment]
Since version 2.1.0, if you are using the Coding Contract API to submit your solution, then the solution for the IP Coding Contract should be given as the string version of your solution array.  For the script

`/UtilScripts/CCTGetter.js`

go to the function

`ipgenerator()`

and change the return statement from

`return validips;`

to

`return validips.toString();`
