### ISSUE TITLE
alias running script on non-existant servers. FREE MONEY

### ISSUE THREAD

**Issue by Ronald-Coone** [danielyxie/bitburner#4169]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by Ronald-Coone** [comment]
alias running script on non-existant servers. FREE MONEY
FIND ME FOR DETAILS

**Comment by Snarling** [comment]
We can't fix the issue if you provide no info.

**Comment by Ronald-Coone** [comment]
I didn't want to leave public info for others to take advantage of...
I'm using an [alias] to run a simple [script]
anything I insert as [arg] becomes a server. 
I'm currently running scripts on 100+ non-existant servers.
Didn't say I wouldn't take advantage!   : - )
AWESOME GAME THO

**Comment by Snarling** [comment]
The issues tab is for you to report issues so that developers can fix them. There are plenty of exploits out there for people who want to cheat, but if there's an issue you want to bring to our attention so we can fix it, then we need information. Otherwise this just doesn't belong as an issue and should be closed.
