### ISSUE TITLE
Hospital unusable - development branch

### ISSUE THREAD

**Issue by steveturri** [danielyxie/bitburner#4242]
If you are missing health and go to the hospital, you can not heal when you click button
Bitburner development branch
![Screenshot (33)](https://user-images.githubusercontent.com/2520418/195599238-0ce1d8f3-9f9f-4e42-8429-ffa33b947611.png)

**Comment by Snarling** [comment]
Not able to reproduce error (using Bitburner v2.1.0 (87054f61) at https://hydroflame.github.io/bitburner/)

1. Started new game
2. Infiltrated joesguns
3. Lost first game (1/10 hp)
4. Cancelled infiltration
5. Visited hospital
6. Was able to heal

![image](https://user-images.githubusercontent.com/84951833/195687843-b09f260e-e098-42c0-8953-0106ab1a036b.png)

**Comment by borisflagell** [comment]
Reproduceable on dev branch. Will look at it.

**Comment by borisflagell** [comment]
It's probably linked to the recent issue with Player/@player import

**Comment by Snarling** [comment]
Yeah I made that todo a while back, thanks for making a nice functional component out of it. I think there are only a few other class components left (the ErrorBoundary which needs to be a class, and BlackJack game are the only other ones I can think of).

Weird that you were able to reproduce the error, I was also on dev and it the button was working normally for me, I wonder what the actual cause was. Seems it was only occurring under certain other conditions.

Based on the error (seems like `this` being undefined while trying to call this.getCost), it shouldn't be able occur with a functional component because there's no longer a `this` to worry about. So regardless of what caused the issue, I think the fix should work.
