### ISSUE TITLE
'kill' not recognizing a running script

### ISSUE THREAD

**Issue by continuum1** [danielyxie/bitburner#4244]
- [bitburnerSave_1665667714_BN1x1.txt](https://github.com/danielyxie/bitburner/files/9777155/bitburnerSave_1665667714_BN1x1.txt)

- [
Script 1: hk_xec.script

--var server = args[0];
--var script = args[1];
--var serverRAM = getServerMaxRam(server) - getServerUsedRam(server);
--var scriptRAM = getScriptRam(script);
--var threads = serverRAM / scriptRAM;
--
--exec(script, server, threads, server);

Script 2: hmhk.script

--while(true) {
--	hack("home");
--}

]

[
-   Start on 'home'
-   do 'run hk_xec.script "home" "hmhk.script"' in terminal
-   do 'kill hmhk.script'
-   receives 'No such script is running. Nothing to kill'
-   do 'tail hmhk.script'
-   tail command generates tail window
-   also, 'running scripts' tab shows hmhk.script running on 'home'
]

I would expect that the kill and tail command would have the same level of access in terms of the running scripts but this result would suggest otherwise

- [v2.1.0]

**Comment by borisflagell** [comment]
It works as intended.

You need to specify the args passed to the script to the kill command. Otherwise, it would not be able to differentiate between two instance of hmhk.script.

Use : kill hmhk.script home 
![image](https://user-images.githubusercontent.com/104104269/195837961-d876da7b-57bb-4147-8cfe-e22a7103c39f.png)
