### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Terminal")

### ISSUE THREAD

**Issue by SiJuBo** [danielyxie/bitburner#4250]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v2.1.0 (8f4636cb)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
* Features: lang=de-DE cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by Snarling** [comment]
Are you using google translate while playing? This seems to be the cause for these issues as all users who have reported this issue use non-english language settings. Google Translate mutates the DOM, and then when React attempts to interact with the content in a specific way, it fails because the content has been mutated without React knowing about it.

https://github.com/facebook/react/issues/11538
