### ISSUE TITLE
NetscriptPort running with incorrect "this" context

### ISSUE THREAD

**Issue by foxxtrot** [danielyxie/bitburner#435]
Currently, any attempts to use functions on a NetscriptPort are failing because this.data isn't set when they execute.

Example Script:
```
port = getPortHandle(8);
port.write("test");
```

Error Output:
```
Script runtime error: 
Server Ip: 3.7.6.7
Script name: test.script
Args:[]
TypeError: Cannot read property 'push' of undefined
```

Checking this function in the JS Debugger suggests that "this" is currently the Script itself. Accessing port.data works correctly, so this can be worked around by messing with "data" directly.

**Comment by kopelli** [comment]
Looks like an issue with the Netscript1 executor. Doing the equivalent in Netscript2 seems to work fine.

**Comment by foxxtrot** [comment]
I think I may have been wrong about being able to work around this by working on the "data" field directly. Trying that doesn't seem to be working.

**Comment by danielyxie** [comment]
The new Netscript 1.0 Interpreter sandboxes everything, so it looks like the `NetscriptPort/getPortHandle()` functionalities can no longer be used (at least not without some modifications that, in my opinion, aren't worth the effort right now). 

These should still work fine in Netscript2.0/JS. 

I will add a note to the documentation that these only work in Netscript2.0/JS.  I will also add `tryWrite()` as a standalone Netscript function so that it can be used in Netscript 1.0.

I'll leave this issue open in case I want come back to implementing the functionality in Netscript 1.0  in the future
