### ISSUE TITLE
Array Jumping game description is confusing

### ISSUE THREAD

**Issue by Kline-** [danielyxie/bitburner#494]
> Each element in the array represents your maximum jump length at that position. Assuming you are initially positioned at the start of the array, determine whether you are able to reach the last index exactly.

At each jump do you _have_ to jump the length of the input, or since it is the _maximum_ jump the jump can range from `[1,input]`?

If you _must_ jump the length of the input then `[18,16]` returning true with the current solver is incorrect.

If you can jump anywhere from `[1,input]` at each step then the solution will _always_ be true because you can keep jumping a single hop each time.

**Comment by danielyxie** [comment]
Its the maximum jump length, so you can jump any number of positions up to that maximum.

The solution will not always be true because its possible for the maximum jump length to be 0. Unfortunately with the current generation 0 rarely shows up (~4% chance). I'll change it so that 0 shows up much more often and we'll see how that goes

**Comment by danielyxie** [comment]
Clarified it a bit in v0.41.0. Feel free to re-open if you think it still needs improvement
