### ISSUE TITLE
Add Monaco as editor option

### ISSUE THREAD

**Issue by freitagdavid** [danielyxie/bitburner#606]
I was thinking of trying to do this myself but I wanted to go ahead and get the temperature of the responses to the idea before I waste my time. I'm a huge fan of vs code and one of the cool things about it is that the actual editor for it Monaco is available as a standalone module. I was wondering how you as well as the community would feel about having an integrated Monaco editor in the game especially seeing as it handles Javascript so well.

**Comment by danielyxie** [comment]
Sorry for the very late response. I am definitely open to adding the Monaco editor as an option. I'd probably want to remove the Ace editor at the same time, though, since there's no point in having & maintaining three different editors.

If you're still interesting in adding this, just let me know and feel free to move forward with it. Otherwise, I'm going to leave this issue open and I'll come back to it in the future.
