### ISSUE TITLE
The game is NP-hard

### ISSUE THREAD

**Issue by BlackCapCoder** [danielyxie/bitburner#655]
The optimization problem of "how do I hack as much money in as little time as possible using N threads" is an instance of the flow shop scheduling problem, which is NP-hard. Is this a deliberate design choice?

There are two factors that make bit-burner difficult:
- The hack, grow and weaken operations take different amounts of time (5, 16 and 20 if I remember correctly)
- How long an operation take is calculated at the time it is invoked, but its result is only calculated upon completion. Thus, you want all operations to be invoked at minimum security - which is after a weakening, but before a hack or grow -, and hack to complete after a grow has completed

The optimal strategy is to pepper as many hack calls at maximum money as tightly as possible, and we can expect finding this optimal ordering to take at least O(k^N) time where N is the number of threads, which is clearly going to become impractical on large servers.

I have also found that creating a separate script for each of these threads (to minimize memory usage) crashes the game for large N.

**Comment by danielyxie** [comment]
Yes!! This is the first time someone has brought the scheduling problem so that's pretty exciting

I learned about scheduling optimization problems in a college algorithms course, and used those to design the game's hacking system. So it wasn't really a conscious choice to make the game NP-hard, but by modeling it after an NP-hard problem I hoped/figured it would be (since I wanted the game to be easy to succeed in but hard to optimize). I never really figured out if the final implementation **was** an NP-hard problem, since I was never great at those proofs, so I guess I'll take your word for it haha

**Comment by BlackCapCoder** [comment]
That's what I thought- it seemed like the system was closely modeled after a scheduling problem! I don't think I have ever seen this done intentionally in a game before, so I figured I'd ask about your reasoning behind it?

I suppose this ensures that the player will never run out of things to do- it will always be possible for them to write a script that is a little bit better.

**Comment by danielyxie** [comment]
Honestly no real reasoning. It was just an interesting problem, could easily fit the game's hacking theme, and I happened to be learning about it when I was initially brainstorming the game's design.

**Comment by hydroflame** [comment]
Not an issue.
