### ISSUE TITLE
Command arguments interpreted as aliases

### ISSUE THREAD

**Issue by KurzedMetal** [danielyxie/bitburner#70]
I did some short aliases for commands I was using regularly and after a while I hit a problem: It seems command arguments are interpreted as aliases too. Definitely not what I was expecting.

```
> run -test.script 6 90 130 0.8 4
Running script with 1 thread(s) and args: [6, 90, 130, 0.8, 4].
May take a few seconds to start up the process...
> alias
alias 3=scan-analyze 3
alias 5=scan-analyze 5
alias 10=scan-analyze 10
alias 11=scan-analyze 10
alias ssh=connect
alias a=analyze
alias g=tail grow.script
alias c=connect
alias s=scan
alias h=home
> run -test.script 5 90 130 0.8 4
Running script with 1 thread(s) and args: [scan-analyze, 5, 90, 130, 0.8, 4].
May take a few seconds to start up the process...
```

It would be nice to have a way to delete an alias too. For example I don't use the "g" one anymore, can't get it out of the list, unless I'm missing something.

**Comment by danielyxie** [comment]
Added a way to delete aliases in v0.22.0

To be honest I'm not sure whether command arguments should be interpreted as aliases. If someone wanted to pass the string "foodnstuff" into a script as an argument and had an alias for "fns=foodnstuff" I would think letting them pass fns in as the argument instead of foodnstuff would be a good thing. Similarly if someone wanted to create a single alias for all of the arguments:

```
alias sargs1="foodnstuff 500000 10" 
run foo.script sargs1
```

I feel like that would be convenient

I'll think about it/get other feedback and I'll leave this issue open for now

**Comment by MrNuggelz** [comment]
I think it would be a good idea to solve this problem by using an alias system like in [zsh](https://www-s.acm.illinois.edu/workshops/zsh/alias.html). There you are able to define aliases which only work at the start of a command, like you would in bash, but you also have the ability to define global aliases which work an any part of a command. This way you are able to use a global alias for parameters but are also able to define normal aliases like above.

**Comment by danielyxie** [comment]
Addressed in next update thanks to MrNuggelz
